### ISSUE TITLE
Disable pagination on repeater fields

### ISSUE THREAD

**Issue by Xilonz** [soflyy/oxygen-bugs-and-features#1002]
**Describe the feature you'd like to see included in Oxygen.**
We'd like to be able to disable pagination on repeater fields, but still be able to have control over the number of posts shown

**What are the use cases for this feature?**
Displaying the latest posts on a front-page.

**Examples of this feature or functionality.**
\-

> I don't need a CSS solution.

**Comment by alexanderkladov** [comment]
I agree, it's dumb that you can't limit this out of the box. It's such a simple solution. WP already has a query var which can probably do the trick and can even potentially improve performance too - [`no_found_rows`](https://github.com/WordPress/WordPress/blob/856e1a27b8dfa9208c36b8b474afcb5acc90322b/wp-includes/class-wp-query.php#L672).

So for now the only solution is to build the query params manually. For example, if you want to get only 10 latest blog posts, the custom query would look like this:

```
post_type=post&posts_per_page=10&no_found_rows=true
```

That would only return 10 posts without pagination.

Of course, you can add all sorts of query vars from [WP_Query](https://developer.wordpress.org/reference/classes/wp_query/) too, to target specific post types, categories, sort things differently etc.

**Comment by Takkster** [comment]
I'd like a simple checkbox for that as well, I practically need to build every query manually or use pre_get_posts.

**Comment by alexanderkladov** [comment]
@Takkster Same here. It's very frustrating. Oxygen Repeaters & Easy Posts are both so powerful, yet this makes them kinda unusable for a novice user. Not everyone knows how to build a manual query string properly. This should be a simple checkbox for sure.

Another nice option would've been if the Manual tab automatically inherited all of the settings from custom configuration tab. That way, at least we could build most of the query using the UI and then switch to Manual and add whatever else is necessary to an already pre-populated Query Params.

**Comment by benfavre** [comment]
in 3.2 even with no_found_rows I get pagination

**Comment by captivation** [comment]
We are looking for this feature as well. I agree that a checkbox would be the best option, "Disable Pagination" or not include it if the query does not return any additional results past the initial request.

**Comment by MattHag** [comment]
It might be posted before advanced query git introduced, nut it is totally unrelated and your suggestions is not a satisfying solution at all.

Quickly use default query and disable pagination? Nope, write an  advanced query to mimic default behavior just to disable pagination. Do you get the nonsense of that (current) approach?

**Comment by alexanderkladov** [comment]
@Spellhammer I agree with @MattHag - Repeater & Advanced Query are 2 completely different modules. This issue was raised for a Repeater module specifically, so it's still valid & is still very frustrating to deal with.

Repeaters are great, because very often you just need something basic, where a Repeater is a perfect solution. But due to it's inability to disable pagination, Repeater module is practically useless out-of-the box. How many times do you need to include pagination on a page? For every repeater element that actually requires pagination, there are at least 10 that don't and you have to manually deal with those every time. It shouldn't be this frustrating.

Especially considering that the solution is so incredibly simple - just add a "Disable pagination" checkbox that, if checked, will add `no_found_rows=true` to an existing repeater query. All it would take is a couple of lines of code.

Or am I missing something? Why can't this be implemented? Are you worried about some compatibility issues? What can this possibly break? I just don't get it..

Unless you are planning on discontinuing Repeaters altogether.. that would explain why this was ignored for 2+ years

**Comment by Spellhammer** [comment]
> It might have been posted before advanced query got introduced, but it is totally unrelated and your suggestions is not a satisfying solution at all.

My suggestion literally satisfies the requirements of the original post: it disables pagination on Repeaters.

I may have misunderstood the request, which is why I asked for feedback.

> Repeater & Advanced Query are 2 completely different modules.

No, they're not. The Advanced Query builder is a feature of the Repeater element.

> But due to it's inability to disable pagination, Repeater module is practically useless out-of-the box. 

You can disable its pagination by using no_found_rows & posts_per_page in your advanced query to prevent the output of pagination on a Repeater element.

>  just add a "Disable pagination" checkbox that, if checked, will add no_found_rows=true to an existing repeater query. All it would take is a couple of lines of code.

I'm not disagreeing that we should do this. I'm gathering feedback as to why we need a checkbox when a few extra clicks gets the same results.

> Why can't this be implemented?

It can.

> Are you worried about some compatibility issues?

Always. But not particularly in this case. It's literally possible to do the thing the request is asking for - you just don't like the implementation.

> Unless you are planning on discontinuing Repeaters altogether.. that would explain why this was ignored for 2+ years

What a strange assumption.

I'm a little concerned that simply asking for feedback as to why the currently available solution isn't satisfactory has prompted such hostile responses.

Regardless, the original request has been satisfied. If you want a checkbox so you don't have to use Advanced Query to disable pagination, please post a new request about that.

**Comment by Zyles** [comment]
> Unless you are planning on discontinuing Repeaters altogether.. that would explain why this was ignored for 2+ years

Money spent on developing Breakdance while Oxygen is on life support.

A simple checkbox would have solved it 2 years ago.

**Comment by alexanderkladov** [comment]
> No, they're not. The Advanced Query builder is a feature of the Repeater element.

@Spellhammer you are right, I don't know why I thought they were separate elements.. Perhaps because Advanced Query was such a massive feature addition/improvement, that I assumed that it was it's own element.

To be completely honest, I haven't touched Repeaters for a very long time now, because historically they were such a pain to work with for me (i.e. where query strings had to be manually written almost every time). So I got into a habit of avoiding them entirely and resorted to raw PHP code blocks instead with proper, editable `WP_Query` args in them. Cos if I was gonna have to build the whole query manually anyway, I'd at least prefer to do it in a way that I can easily edit in the future, plus will get complete control of the resulting output code too.

So I guess some of my statements do not apply, since advanced query builder is, indeed, a part of the Repeater element. Sorry for the confusion. And I definitely didn't in a hostile way, I simply listed my reasoning & past frustrations with the Repeater element.

Having said that, I disagree with your decision to close this issue as "resolved". Because, in my opinion, it's not resolved the way it was requested. I believe this will continue causing problems for inexperienced WP devs. Most people won't know that they ABSOLUTELY HAVE TO set `no_found_rows` to `true` if they want to get rid of pagination. It's incredibly counter-intuitive & is not documented/explained properly by WP team (outside of poorly-elaborated comments in [class-wp-query.php](https://github.com/WordPress/WordPress/blob/856e1a27b8dfa9208c36b8b474afcb5acc90322b/wp-includes/class-wp-query.php#L672)). One would reasonably assume that that setting `nopaging` to `true` (found under Pagination group in your Advanced Query builder btw) would get rid of pagination, but it doesn't - it will do something completely counter-intuitive and instead list all posts, even ignoring `posts_per_page` limits. It's ridiculous & is not Oxygen Builder's fault at all, but is simply what WP does. Or, you might think that you can set `paged` to `false`, but that's also not it - it doesn't accept BOOL values at all, that arg's purpose is completely different, even though the naming is suggestive. The only thing that gets rid of pagination entirely is `no_found_rows` set to `true` and nothing else (nothing that I found anyway). Therefore, in my opinion, it has be something as simple as a click of a button, at least inside the basic query builder found under Repeater > WP Query > Custom > Count. And for those who want to build the query using Advanced Query builder, perhaps at least move (or duplicate) `no_found_rows` to the Pagination group (because right now it's under Caching, which is also what it's for, but it also controls pagination).

Speading of Advanced Query, would be awesome if you added some sort of simple tooltip/descriptions for the default listed WP Query args. Something that would describe what that argument does and what type of variable it accepts (string/bool/int etc). That would make query building a lot easier and won't require digging through WP docs as often. Those simple descriptions could be copied from [WP Query args code comments](https://github.com/WordPress/WordPress/blob/856e1a27b8dfa9208c36b8b474afcb5acc90322b/wp-includes/class-wp-query.php#L611-L740) directly. Some, like `no_found_rows`, would have to be described better though, because the way WP describes it is not how people actually use it.

**Comment by MattHag** [comment]
Continuation, vote here
https://github.com/soflyy/oxygen-bugs-and-features/issues/3118
