### ISSUE TITLE
Bad video embed code

### ISSUE THREAD

**Issue by gtrusler** [soflyy/oxygen-bugs-and-features#1005]
When I use the video element on a page and enter the URL (not the embed code), the original example URL is left in the source of the rendered page. Here is the iframe code that gets generated:

<iframe src="https://www.youtube.com/https://vimeo.com/244152319watch?v=qgcX0y1Nzhs" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

**Comment by KittenCodes** [comment]
@gtrusler Please ensure you are deleting the original YouTube video URL before adding the Vimeo URL. I've done this on the Sandbox site here and the iframe source is correct: https://oxygen-q2xmgvzl4kz8k.oxygen-demo.qsandbox.me/video/.

If this isn't working for you, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
