### ISSUE TITLE
The package could not be installed. The theme is missing the style.css stylesheet.

### ISSUE THREAD

**Issue by larry790607** [soflyy/oxygen-bugs-and-features#1033]
N

**Comment by jamescrabb** [comment]
Not a theme. Read the official docs properly. Again not a theme

**Comment by d-packs** [comment]
This is not a proper bug report. The error might be legit and suggests some conflict with some plugin, although i don't understand what 'package' could be. But again it is nobody's job to guess at what the OP tried to report. Please file e proper report. Describing what you did to get the error, how to reproduce, expected behavior, etc.

**Comment by jamescrabb** [comment]
> This is not a proper bug report. The error might be legit and suggests some conflict with some plugin, although i don't understand what 'package' could be. But again it is nobody's job to guess at what the OP tried to report. Please file a proper report, describing what you did to get the error, how to reproduce, expected behavior, etc.

They have clearly tried to upload oxygen as a theme rather than a plugin

**Comment by Spellhammer** [comment]
Upload Oxygen as a plugin rather than a theme and you won't receive this error.

**Comment by Milah3** [comment]
Hahaha. Thanks
