### ISSUE TITLE
dragging problem 

### ISSUE THREAD

**Issue by tech2win** [soflyy/oxygen-bugs-and-features#1065]
1. I created a column inside a section and then make two div inside one with image and another one with heading and text but when im trying to locate in structure column showing me as a text.(check screenshot)
2. it's very tough to drag things around like up and down, right and left sometimes it's very irritating...
3. some time user toolbar on front-end not appearing (yes i already checked in Show Toolbar when viewing site)
im using windows 10 and 7 and browser chrome and Firefox  
![Untitled-2](https://user-images.githubusercontent.com/3313308/80168671-15f9c080-8601-11ea-954d-e5ef1dc7af20.jpg)

**Comment by KittenCodes** [comment]
@tech2win 

> when im trying to locate in structure column showing me as a text

Please open a support ticket so that we can take a look at this issue for you: https://oxygenbuilder.com/support.

> some time user toolbar on front-end not appearing

I suspect this is caused by a plugin conflict. Does the issue persist when Oxygen is the only active plugin? If it happens when Oxygen is the only active plugin, please include a link to the page in your support ticket.
