### ISSUE TITLE
Oxygen Builder and LiteSpeed Cache Wordpress plugin not compatible?

### ISSUE THREAD

**Issue by Labona** [soflyy/oxygen-bugs-and-features#1077]
Hey,

So I installed fresh copy of Oxygen to my fresh new Wordpress website.
When I entered to to builder I am seeing it messy (Icons are double times).

I troubleshooted that when I have LiteSpeed Cache -Wordpress Plugin  (which optimize my wordpress site performance + lazy load images) this problem starting.

![image](https://user-images.githubusercontent.com/64415521/80373637-a6e8ca00-8895-11ea-88cd-82fcc24c8026.png)

![image](https://user-images.githubusercontent.com/64415521/80373659-aea86e80-8895-11ea-80fa-ddfa9f3318b3.png)

So I just wanted to make sure if the Oxygen is compatible with this plugin? This plugin is really common when you have Litespeed server.

Thanks a lot for any advices or help how I can get both working together.

**Comment by louisreingold** [comment]
Configure the cache to not mess with Oxygen's files and dependencies.

**Comment by Labona** [comment]
Well yes I can confirm that LiteSpeed Cache plugin works perfectly with Oxygen Builder. I am not sure what caused the problem but has to be some settings / configurations. Because I can't reproduce the problem on my other server where I have installed also Oxygen Builder + Litespeed Cache plugin :) There both works perfectly.

**Comment by SimonErich** [comment]
I had the same issue and found a solution.
The problem seems to be image lazyloading, that replaces code in the compiled angular files, but the code is probably not escaped and therefore produces problems.
I managed to fixed it by just excluding oxygenbuilder pages in litespeed from image lazyloading.

you can find it under 
"Litespeed" -> "Page Optimizations" -> "Media Settings"
And then just find the textarea "Lazy Load URL Excludes" and add the following in a line:
```
?ct_builder=true
```

Hope this helps :)

![Screenshot from 2021-03-15 08-18-47](https://user-images.githubusercontent.com/6395538/111116973-21324380-8567-11eb-9a80-8a99dddb2147.png)

**Comment by Anticosti** [comment]
For me the trick is to make sure that the Administrator is not being cached.
![image](https://user-images.githubusercontent.com/5446224/111165516-82f9aa00-8575-11eb-87c2-e8223ed5e968.png)
![image](https://user-images.githubusercontent.com/5446224/111165527-868d3100-8575-11eb-8d4f-643d58eb8fc1.png)
