### ISSUE TITLE
Custom Design library not loading nor working properly on localhost

### ISSUE THREAD

**Issue by runechronos** [soflyy/oxygen-bugs-and-features#1082]
Hy,

I can't manage to get a **Page** as a design library part. I'm working on my localhost using my IP adress to access it from my local network. 

I checked both **include the sections in this page in the library** and "**include this entire page in the library** and I selected a category, on the design set options of the Page I want to add to the design library.

When I press **Generate screenshots** , it loads, and it writes **Screenshots generated successfully ** but I get a **chrome popup message** telling me **You must have a valid license to do this**. Yet I filled my licence properly in the settings, and it is written **valid** next to the hidden license number. And when I publish/update the page, I still get the message **Screenshots have never been generated**

I also checked **Enable default design set & Make this Wordpress Install a Design Set** in the library settings tab.

When I go the a Page and try to add an element from my new design set, I see the design set in the list, but when I click on it I get this message : **Items not loaded. Not found** and nothing happens.

I cleared the **CSS cache** and **resigned the shortcodes** like 3-4 times, still nothing, restarted my Apache server many times too.

I don't understand what's going on and what may be wrong.

Could you help me with this ?

It's quite annoying, I only wanted to duplicate the page... Not even to really use it in the library for another project.

Thanks in advance.

**Comment by KittenCodes** [comment]
@runechronos 

You can duplicate the page by clicking the +Shortcodes button below the "Edit with Oxygen" button. You need to copy the shortcodes from the existing page to the new page.

Unfortunately, we're not able to troubleshoot local installs. However, if the issue persists once your site is running in an accessible environment, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.
