### ISSUE TITLE
Inability to save templates with emojis

### ISSUE THREAD

**Issue by kancur** [soflyy/oxygen-bugs-and-features#1176]
Hi there! 

Whenever you use an emoji in a text field, rich text field, heading, etc. and you hit save, nothing happens (no error message or anything) - but the template is not saved. You have to delete the emoji and then the saving works.

This issue occurs regardless of your "disable emojis" setting.

**Comment by Spellhammer** [comment]
Are you able to save emojis in normal WordPress fields, like post content and title?

**Comment by kancur** [comment]
Yup, no problem with that. Tested it right now.

**Comment by KittenCodes** [comment]
@kancur I suspect this may be caused by the database collation or table encoding on your site. You will need to make sure that your database and tables are encoded with utf8mb4_general_ci or utf8_general_ci. If you're not sure how to do this, please contact your web host.

If your database and tables are encoded correctly, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by kancur** [comment]
Hi @KittenCodes, You are correct. My tables used **utf8_unicode_ci** collation, I've changed it to **utf8mb4_unicode_ci** which solved the problem. Thank you for your help!

**Comment by KittenCodes** [comment]
No problem!
