### ISSUE TITLE
Support for ACF options

### ISSUE THREAD

**Issue by sigersmit** [soflyy/oxygen-bugs-and-features#1247]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
Right now Oxygen does not support the fields created within an [ACF options page](https://www.advancedcustomfields.com/resources/options-page/) 

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
We use the ACF options page to store (site wide) company info, like phone numbers, adresses, e-mail adresses for clients easy to change everywhere on the website.
Right now to use this data in Oxygen templates we have to use the PHP function return value. It would be great if this could be treated like the normal ACF data. Even greater if this data also can be used as data for links etc. (so the e-mailadress is dynamically linked in the URL field) 

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
Elementor does have this functionality. With links you can also add a append before or after lik tel: or mailto:

**Comment by aleklisefski** [comment]
+1

**Comment by Zyles** [comment]
Needed really badly for global data.

**Comment by BrynWithin** [comment]
PLEASE can this be added as soon as possible. The pain and misery caused by needing to use code blocks and PHP function return values is real. Given how central dynamic data is to Oxygen, I don't understand why this hasn't been added yet! Options pages with ACF are massively useful as it lets clients control global information contained in templates that they don't have access to.

**Comment by noodleyness** [comment]
+1 for this please!!

**Comment by adrien-robert** [comment]
+1

**Comment by wpsumo** [comment]
+1

**Comment by KittenCodes** [comment]
To retrieve an ACF field from an Options page, you need to click Insert Data > PHP Function Return Value. You need to use the function name get_field and then enter the arguments:

my_field,option

You need to replace my_field with the name of the field you want to retrieve. Please also ensure there are no spaces in the arguments field.

**Comment by jamescrabb** [comment]
@KittenCodes 

Is this something that can be integrated natively? Or rather this is something that should be natively integrated.

**Comment by Zyles** [comment]
> To retrieve an ACF field from an Options page, you need to click Insert Data > PHP Function Return Value. You need to use the function name get_field and then enter the arguments:
> 
> my_field,option
> 
> You need to replace my_field with the name of the field you want to retrieve. Please also ensure there are no spaces in the arguments field.

This is a workaround.

**Comment by KittenCodes** [comment]
> Is this something that can be integrated natively? Or rather this is something that should be natively integrated.

Native integration for ACF Options pages comes up a lot, so I have left the feature request open. The reason that I added the workaround above is so that people can see how to retrieve their data.

**Comment by wpsumo** [comment]
@KittenCodes don't think it works for repeaters though to fetch with Oxygen repeaters from ACF repeaters on options page using post object.

**Comment by damienbailey** [comment]
Please include this in your integration. I was trying to setup a Business details option page so there was only one place to update this data.

Maybe this should be labelled as bug rather than a enhancement. Fields that are setup in an options page are showing in your integration. If they are available they should be working rather than just saying no data for field.

**Comment by albertvisuals** [comment]
+1

**Comment by tD3rk** [comment]
This is mission critical. The workaround of PHP return value is fine for text fields/etc. but cannot be used for repeaters.

**Comment by katsar0v** [comment]
Any update on this long waited feature? It would be great if we could define the loop with code by ourself somehow

**Comment by KittenCodes** [comment]
ACF Options support added in Oxygen 3.9 Beta.

**Comment by wpsumo** [comment]
@KittenCodes Would it be possible to display ACF data via meta field name instead of the name, as it's normally easier to find and better naming convention that way. As we might name for users one way but for ourselves building the sites we use the meta field. It would be more inline how you work with it in code you fetch the meta_value not the name of the field.

This way the workflow would be more streamlined, displaying the meta name over the name.

Default - field for users
`default_user_field`

as we use get_field() with meta field not the name.

Would also appreciate if we could have a better UI listing them better than boxes and use a search field.
