### ISSUE TITLE
xlink=css URLs still generated

### ISSUE THREAD

**Issue by plittlefield** [soflyy/oxygen-bugs-and-features#1274]
In the release notes for version 2.2, it states that "There are no more xlink=css URLs, which some caching plugins and CDNs did not like."

https://oxygenbuilder.com/2018/11/30/oxygen-2-2-alpha-1-now-available/

However, when using version 3.3.1 on my site, there is still a line for this type of meta code:-

e.g.

`<link rel="stylesheet" id="oxygen-styles-18-css" href="https://mywebsite.com/?post_id=18&#038;xlink=css&#038;nouniversal=true&#038;ver=5.4.2" type="text/css" media="all">`

It does not seem to display anything and wondered if it's possible to remove it?

**Comment by amiralbatal** [comment]
me too

**Comment by Spellhammer** [comment]
Is "Enable CSS Caching" checked under Oxygen > Settings > CSS Cache in the WordPress admin panel?

If it is and you're still seeing an xlink CSS file generated, please submit a support ticket via https://oxygenbuilder.com/support.

Otherwise, checking it should prevent Oxygen from generating an xlink CSS file.
