### ISSUE TITLE
Oxygen Builder will install Proteus from the Oxygen library

### ISSUE THREAD

**Issue by forcedlogic** [soflyy/oxygen-bugs-and-features#1305]
Using local by flywheel. Oxygen will not install Proteus from the Oxygen library. Every other template shows up fine this one will not show up no matter what you do. The page appears are unstyled text without CSS. Not templates such as main, or others are showing up under templates either.

**Comment by KittenCodes** [comment]
@forcedlogic 

The Proteus design set doesn't contain any templates. It adds one page called UI Kit. If the UI Kit page styles aren't loading correctly, we would need to take a look at your site to find why. If you're able to clone your site to an accessible environment, please open a support ticket so that we can advise further: https://oxygenbuilder.com/support.
