### ISSUE TITLE
Error with shortcode from WPForms

### ISSUE THREAD

**Issue by jlebouch76** [soflyy/oxygen-bugs-and-features#1327]
**Describe the bug**
I'm experiencing error (line 18) when putting wrapping a shortcode in a div, or when moving a shortcode into an existing div. 
And right after closing the first error message, i can't click on any element of my page... few seconds later i get error (line 1). 
This happens with shortcodes from free WPForms plugin. I'm using Oxygen 3.4, Macbook, and Chrome.

<img width="415" alt="Screen Shot 2020-07-11 at 9 37 57 AM" src="https://user-images.githubusercontent.com/7088227/87219363-a4592500-c35a-11ea-8209-08674714df38.png">

<img width="454" alt="Screen Shot 2020-07-11 at 9 38 10 AM" src="https://user-images.githubusercontent.com/7088227/87219358-93101880-c35a-11ea-9a3e-3b489a9e7aa6.png">

**Comment by KittenCodes** [comment]
@jlebouch76 Please use a Shortcode element and not a Shortcode Wrapper element. If that doesn't help, please run a plugin conflict test to see if another plugin is causing the error (leave Oxygen and WPForms active): https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.

If that doesn't help, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
