### ISSUE TITLE
product variable images

### ISSUE THREAD

**Issue by aamjoune** [soflyy/oxygen-bugs-and-features#1400]
Hello,
I have a problem and that is when i activate oxygen builder the variations of images does not work it only chages the price and inventory availabality.
I made all tests and i found that oxygen is the plugin that does not allow variations of images work correctly.
Can you help me please?

**Comment by aamjoune** [comment]
here the loom video; https://www.loom.com/share/6868f3aa45964e9fb381e57b3a717475

**Comment by KittenCodes** [comment]
@aamjoune 

> I have a problem and that is when i activate oxygen builder the variations of images does not work it only chages the price and inventory availabality

Variation images usually change automatically when a variation is selected - you can see it working correctly on the page here: https://oxygen-qjt8r6pbldtal.oxygen-demo.qsandbox.me/product/ship-your-idea-2/.

As this isn't working correctly for you, please run a plugin conflict test: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/. If the issue persists when Oxygen, WooCommerce and Oxygen's WooCommerce add-on are the only active plugins on the site, please open a support ticket so that we can take a look; https://oxygenbuilder.com/support.

**Comment by aamjoune** [comment]
Good morning,
I did all the tests you told me.
1- I deactivated all plugins but woocommerce --> image variations work fine.
2- I deactivated all plugins except woocommerce and Oxygen Elements for
WooCommerce --> image variations work fine.
3- I deactivated all plugins except woocommerce and Oxygen Elements for
WooCommerce and _*Oxygen itself*_ --> *image variations does not work.*
Please help me.
I also opened a support ticket as you told me. VARIATION IMAGES DOES NOT
WORK WHEN ACTIVATE OXYGEN #1425THANK YOU IN ADVANCE.
BEST REGARDS.

**Comment by KittenCodes** [comment]
@aamjoune Please open a support ticket: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help" instead of opening an issue on GitHub.
