### ISSUE TITLE
Shop Page padding is lost and not working any more

### ISSUE THREAD

**Issue by bchangia** [soflyy/oxygen-bugs-and-features#1440]
**Describe the bug**
*A clear and concise description of what the bug is.*
https://share.getcloudapp.com/E0un4R2K Link screenshot of the Shop template builder, its looking great here with the padding setup on all 4 sides.

But boom on the main page its lost?

Looks like oxygen builder is loosing its stability and we have to look for alternative option now. With so many bugs coming up its very difficult to trust the robustness of the plugin

**Comment by bchangia** [comment]
https://chang.host/store/ link to page's final view

**Comment by bchangia** [comment]
now it looks like we as a customer have become a tester and bug reporter for this product.

**Comment by bchangia** [comment]
there is no one to answer on the bug?

**Comment by KittenCodes** [comment]
@bchangia It looks as though your template isn't assigned correctly. First off, please try setting a higher priority on the template. If that doesn't help, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You ned to click "Something's broken and I need help".
