### ISSUE TITLE
Error 500 editing a page

### ISSUE THREAD

**Issue by ciberosv** [soflyy/oxygen-bugs-and-features#1477]
Sometimes when I start to edit one page with oxygen builder it shows me this message:

> Error occurred while rendering the component
500
Your server returned a 500 error for the request to [myurl]

1. Go to 'pages'
2. Click on 'All pages'
3. Click on 'Edit with Oxygen' link of Page card

![2020-08-16_10h55_49](https://user-images.githubusercontent.com/5110030/90988948-5f7cfc80-e55c-11ea-851c-3937b5cb67ea.jpg)

Desktop:
- OS: Windows 10 Home
 - Browser: Chrome, Opera, Firefox and Vivaldi
 - Oxygen Version: 3.4

It appears somethimes and only on that page

**Comment by KittenCodes** [comment]
@ciberosv A 500 error is a server-generated error. It most commonly occurs when your site runs out of memory, but there can be other causes. Please contact your web host and ask them to check the server error logs for issues.

If the logs are empty or they're not able to find anything, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
