### ISSUE TITLE
The color picker is not showing.

### ISSUE THREAD

**Issue by badhon861** [soflyy/oxygen-bugs-and-features#1479]
**Describe the bug**
*The color picker dosesn't show up*

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*No*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
I just tried on the Sandbox and the problem is not there.

**Screenshots**
https://tinyurl.com/y4v9zzq6

**Desktop (please complete the following information):**
- OS: [Windows 10]
 - Browser [e.g. chrome]
 - Oxygen Version [3.4]

**Comment by KittenCodes** [comment]
Duplicate: #1417 

​In WordPress 5.5, the jQuery Migrate 1.4.1 script has been removed and as such, it prevents Oxygen's colour picker from working correctly. We're aware of the issue and it has been fixed in Oxygen v3.5, which is currently in RC. If you want to use the RC, you can get it from the customer portal: https://oxygenbuilder.com/portal.

Alternatively, you will need to downgrade to WP 5.4 until the final version of Oxygen v3.5 is released.
