### ISSUE TITLE
Styling classes does not work with CSS caching

### ISSUE THREAD

**Issue by Zyles** [soflyy/oxygen-bugs-and-features#1497]
**Describe the bug**

When you create a class which is shared among multiple items and edit the style it only shows correctly in the editor.

When you enable CSS caching and regenerate the cache, the frontend has the wrong styles and the shared CSS class styles are not applied.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes

**To Reproduce**

1. Create multiple items that share a class
2. Edit the styles of the class
3. Enable CSS caching and regenerate cache
4. View the frontend the CSS classes are not applied (but works in the editor)

**Expected behavior**

CSS for classes should generate for the cache and work in frontend.

**What actually happens**

CSS not generated and styles are not applied.

**Comment by KittenCodes** [comment]
@Zyles This isn't normal behaviour. First off, please run a plugin conflict test to see if another plugin on your site is preventing the changes from being applied: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.

If that doesn't help, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support. You need to click "Something's broken and I need help".
