### ISSUE TITLE
Possible Conflict with Insert Header & Footer Plugin

### ISSUE THREAD

**Issue by MetalPromo** [soflyy/oxygen-bugs-and-features#1502]
**Describe the bug**
When I activate "Insert Header & Footer" I am not able to open the oxygen builder. Video of issue can be found here: https://www.loom.com/share/59d55fca67884e36a777adcaacf805ae

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**To Reproduce**
1. Activated Insert Header & Footer
2. Went to Oxygen Builder
3. Unable to edit in oxygen builder
5. Disable Insert Header & Footer
6. Return to oxygen builder
7. Error not present when plugin is disabled

**Expected behavior**
When I activate insert header and footer then oxygen builder becomes unusable

Are there any other plugins that can be used that will not break the oxygen builder?

**Comment by KittenCodes** [comment]
@MetalPromo 

I wouldn't expect the Insert Headers and Footers plugin to cause this type of issue - it's most likely caused by the code that has been added to the Insert Headers and Footers plugin.

I've installed the plugin on the Sandbox site here and you can see the builder is working correctly: https://oxygen-qmzlyjppjz3al.oxygen-demo.qsandbox.me/?qcmd=auto_login&user=demo&pass=demo&next=admin.

You will need to go through the code you've added to the Insert Headers and Footers plugin to determine what is causing the issue.
