### ISSUE TITLE
Slider issue

### ISSUE THREAD

**Issue by etiennemansard** [soflyy/oxygen-bugs-and-features#1519]
**Describe the bug**
I have created a slider over a video background. The slider consists of 4 words that fade in and out. The issue is when you load the page at first, for a second, the slider shows all the words with bullets which doesn't look pretty at all (on Chrome) or all the word on top of each other (Safari).

*A clear and concise description of what the bug is.*
Already described above.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Dunno what's Sandbox.

**To Reproduce**
1. Go to https://www.clearlightclinic.co.uk/
2. Look at the hero video header title (in pink)
3. Here is a screenshot of what it looks like: https://www.dropbox.com/s/gv69lwsn36kf2xa/Screenshot%202020-09-08%20at%2013.34.13.png?dl=0

**Expected behavior**
When you launch the home page, the first word/slide of the slider should show, not all the word at once 

**What actually happens**
All the word from each slide show all at once for a second 

**Screenshots**
https://www.dropbox.com/s/gv69lwsn36kf2xa/Screenshot%202020-09-08%20at%2013.34.13.png?dl=0

**Desktop (please complete the following information):**
- OS: Mac OS Catalina 10.15.6
 - Browser: Chrome / Safari
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
- Device: iPhone
 - OS: iOS 13.7
 - Browser: Chrome / Safari
 - Oxygen Version 3.5

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@etiennemansard 

This happens because the slider loads in the page before all of the associated code has had chance to load. To fix it, please add the class "hide-slider" to the Slider and set the visibility to hidden via Advanced > Layout. You then need to add a Code Block element to the top of the page with the following code on the JavaScript tab:

jQuery(window).load(function() { 
  jQuery('.hide-slider').css('visibility','visible');
});


You will now see a white space while the page loads and then the first slide will be shown.

**Comment by etiennemansard** [comment]
Hello,

It worked: Thanks!


Etienne

**Comment by eyesolutions** [comment]
Hi.  I have a slider on home page.   www.eyesolutions.in.

I was facing the same issue only on a mobile.   Did everything as mentioned.  Added code on home page as well as on main template.  The slider becomes invisible but the first slide does not appear.

Please help

Thank you
