### ISSUE TITLE
color picker for text and other color selection has disappeared again

### ISSUE THREAD

**Issue by visualtribe** [soflyy/oxygen-bugs-and-features#1530]
**Describe the bug**
The bug where the circle color selector is gone again or when you type in the hex, a square box appears. 

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes/No*

Your sandbox is not at the current Wordpress 5.5.1 version

**To Reproduce**
1. go to WordPress page and launch Oxygen
2. place div tag, text, head, section and pick color of the element
3. no circle white icon appears nothing for color picker

**Expected behavior**
*A clear and concise description of what you expected to happen.*
color picker works

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
no circle. Have to type in hex. The color square appears

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![Screen Shot 2020-09-11 at 3 50 04 PM](https://user-images.githubusercontent.com/11344074/92975908-98670d80-f446-11ea-9a4d-d0caf54ab778.png)
![Screen Shot 2020-09-11 at 3 49 58 PM](https://user-images.githubusercontent.com/11344074/92975911-99983a80-f446-11ea-97f7-5fb8577c12aa.png)

**Desktop (please complete the following information):**
- OS: Mac
 - Browser Firefox
 - Oxygen Version 3.5

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
@visualtribe Please update Oxygen to the latest version (v3.5). If you continue to have problems after updating, or you're already running the latest version of Oxygen, please run a plugin conflict test: https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/.

If that doesn't help, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.
