### ISSUE TITLE
Dynamic oxygen data dont show until i click update post button. Is it normal behaviour? 

### ISSUE THREAD

**Issue by zbyneksmetana** [soflyy/oxygen-bugs-and-features#1738]
**Describe the bug**
I install CPT UI plugin and import "custom posts type"  from another domain by "WP Import Export Lite" plugin (export xml file from one domain and import to another ).  This posts have ACF fields.

I create Oxygen template for this post type and **add "Oxygen dynamic field"** inside "Oxygen text block". This dynamic fields not show up **until I click the Update button in each post** (under Wrdpress  editor not oxygen ).

I try also show this dynamic data by paste php into template  .. for example  the_field('specific_acf_field_name') and it works ok.

**Is it normal behaviour ? I mean that I need to update each post?**

P.S. Sorry for language mistakes

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Comment by KittenCodes** [comment]
> I create Oxygen template for this post type and add "Oxygen dynamic field" inside "Oxygen text block". This dynamic fields not show up until I click the Update button in each post (under Wrdpress editor not oxygen ).

I suspect this is happening because the plugin you are using to import your posts isn't creating the ACF fields correctly. Each ACF field has two parts and both need to be present in the database. When ACF fields have been incorrectly imported, clicking the "Update" button in the WordPress admin area causes the other field to be created, which is why it starts working.

You would either need to go through all of your posts and click the "Update" button, or re-import the posts using a plugin that has ACF support, such as WP All Import: https://www.wpallimport.com/.

**Comment by zbyneksmetana** [comment]
Sounds reasonably (i dont know how ACF works inside). 

I try also inside Oxygen [ACF ...] shortcode and "sometimes works sometimes not".
 
By the way i use Soflyy plugin 
https://www.wpallimport.com/
with combination
https://wordpress.org/plugins/wp-import-export-lite/
and php function.

I try do it without paying/pro version ... I only need this to one website.

**Comment by KittenCodes** [comment]
You need to get the ACF add-on from WP All Import to be able to import ACF fields.
