### ISSUE TITLE
Templates randomly missing contents

### ISSUE THREAD

**Issue by shmaltz** [soflyy/oxygen-bugs-and-features#1739]
**Describe the bug**
At random times when opening a template to edit it, it is missing some contents (sections, divs, modals, etc). Some times it does not show anything at all, even in the structure pane. At other times just a few elements are missing. Also, on the frontend, these elements (and sometimes the whole template) disappears. Weird part is, that when viewing the templates shortcodes on the wp edit template page, it appears that everything is where it should be. Additionally, going back to an old revision does not solve this issue. This is getting very frustrating as it is happening more often than not. At one point my header footer template wasn't working on my site for over an hour.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**To Reproduce**
This happens randomly when I attempt to edit the template and save it.

**Expected behavior**
My entire template should display properly.

**What actually happens**
The template is either missing parts or missing entirely

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Oxygen Version 3.7
 - WP Version 5.5.3

**Additional context**
The only way I found that sometimes helps me get back to my old working template is a mixture or resigning shortcodes, clearing oxygen cache and clearing my server cache. Sometimes it works and at other times it doesn't. 
I think I only started facing this issue since version 3.6, but it may have been earlier.

**Comment by KittenCodes** [comment]
@shmaltz Please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by perrelet** [comment]
I have seen this behavior on various builds / versions of oxygen. It's challenging to provide a bug report despite knowing the oxygen source intimately because it is highly spontaneous and difficult to reproduce. We just lost spontaneously lost the front page to a high traffic website this way. Restored via a revision, however client is necessarily upset. I've seen this happen predominantly to the 'catch all' templates. That's about as much as I know about this bug. It's there and one of the reasons our agency no longer uses oxygen.
