### ISSUE TITLE
Firefox vs Chrome VH height Display

### ISSUE THREAD

**Issue by ducktape4004** [soflyy/oxygen-bugs-and-features#1829]
**Describe the bug**
Problem : The height of the VH display does not match between Google Chrome and Firefox browser

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes
https://oxygen-qm9a99d4kkycl.oxygen-demo.qsandbox.me/?ct_template=page-template&ct_builder=true&ct_inner=true
https://oxygen-qm9a99d4kkycl.oxygen-demo.qsandbox.me/firefox-vs-chrome-display/

**To Reproduce**
1. Add VH height to Section, DIV or other in page or post
2. Reduce VH percentage so that it may display be visible on Full page or post
3. Display in Firefox and compare display in Chrome (scroll up/down)

**What actually happens**
Page height are different for each browser

**Screenshots**
See Sandbox

**Desktop (please complete the following information):**
- OS: Windows 10
 - Firefox 84.0.2 (64-bit)
 - Chrome 87.0.4280.141 (Official Build) (64-bit)
 - Oxygen Version [e.g. 2.2 Alpha]

**Smartphone (please complete the following information):**
 - Oxygen Version 3.6.1

**Comment by KittenCodes** [comment]
@ducktape4004 I suspect it's not the vh setting that's different, but more likely the way the different browsers are reading the elements that make up the header and footer.

If you check the page here: https://oxygen-qm9a99d4kkycl.oxygen-demo.qsandbox.me/vh-test/, you will see a 5px border around the Section in both Chrome and Firefox, which shows that the 100vh setting is working correctly.

If you need help setting a Section to 100vh minus the height of the header and footer, please open a support ticket so that we can take a look: https://oxygenbuilder.com/support.
