### ISSUE TITLE
Hello! I`d like to see the border option for the whole site. Border like frame around screen on the page.

### ISSUE THREAD

**Issue by Barinburo** [soflyy/oxygen-bugs-and-features#186]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by Infusednl** [comment]
Hi Barinburo,

Can't you just add a div that has a border in your main template that wraps the whole website? This should be really easy to do. I always have a div with the class '.site-wrapper'.

Do this and add a border to the div with the class '.site-wrapper' and you're done.

`.site-wrapper {
  display: block;
  position: relative;
  width: 100%;
  min-width: 100vw;
  height: 100%;
  height: 100vh;
  border: 10px solid #000; // Change the border to your liking
}`

If you want a border that encompassed the screen and always stays put regardless of scroll position.
Then add a div that is fixed with the border. You use the following css in that case:

`.fixed-site-border {
  display: block;
  position: fixed;
  width: 100vw; // Take up 100% of the viewport width
  height: 100vh; // Take up 100% of the viewport height
  border: 10px solid #000; // Change the border to your liking
  z-index: 9999; // Use a high number to make sure the border is above everything else
}`

If I understand your question correctly one of these options should work. Otherwise send me a message and I gladly help you out.

Cheers,

Christiaan
