### ISSUE TITLE
If Non-English characters in page slug, CSS doesn't load

### ISSUE THREAD

**Issue by dogstar10** [soflyy/oxygen-bugs-and-features#1871]
**Describe the bug**
If a page slug is, for example, in Hebrew then the CSS file created for this page is unreadable by the browser.
Oxygen saves the page's CSS with the page slug and template ID as the name of the CSS file.

for example, if an About page in Hebrew is called 'אודות' then the CSS created is named %d7%a9%d7%a9%d7%a9%d7%a9%d7%a9-146.css, which is the encoded page slug.

this file gives me a 404 error in firefox.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://shiny-porcupine.w5.wpsandbox.pro/%d7%90%d7%95%d7%93%d7%95%d7%aa/

**To Reproduce**
1.create page with non-english slug
2.edit page with oxygen
3.open page in browser
4.see that no styles are shown on the page, 404 error in dev console for page CSS

**Expected behavior**
Styles should be shown

**What actually happens**
Styles aren't shown

**Desktop **
- OS: windows 10
 - Browser: tested on Firefox and Chrome
 - Oxygen 3.6.1

**Comment by pimpawell** [comment]
+++

**Comment by fdk3r6b** [comment]
+++ me to

**Comment by KittenCodes** [comment]
You may be able to use this plugin as a workaround: https://wordpress.org/plugins/cyr2lat/.

**Comment by pimpawell** [comment]
> You may be able to use this plugin as a workaround: https://wordpress.org/plugins/cyr2lat/.

but if you have already created a page with a non-English slug, further changing it will not help and css will not work

**Comment by zviz** [comment]
this bug is been forcing me to work in latin characters.
i have 2 clients now with woocommerce sites that have thoushands of products in hebrew and i can not waste their time on translating it.
pls work this thing out because it is ruining my chances to promote oxygen as a tool for the Israeli market.

**Comment by v-marinkov** [comment]
This is indeed an important issue and I hope a solution or workaround is implemented soon.

**Comment by robert1112** [comment]
I have a similar issue. I use Chinese URL. I also see the console warning `Refused to apply style from 'https://cdn.site.tw/wp-content/uploads/oxygen/css/%e8%ae......b9%b3-31.css?cache=1632897780&ver=5.8.1' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

**Comment by KittenCodes** [comment]
Fixed in v3.9 Beta 1.
