### ISSUE TITLE
Displaying Elements as table like in the example below.

### ISSUE THREAD

**Issue by cliv3ne** [soflyy/oxygen-bugs-and-features#1875]
Is it possible if we can add a displaying the elements as a table, for example, I have a menu list, basically the menu list on wordpress is constructed as a ul>li element. So what I wanted to happen is the "ul" element will be styled as "display : table; width : 100%;" while on the "li" element is "display: table-cell;" where the list of items will occupies the whole table as a table-cell.

**Comment by KittenCodes** [comment]
@cliv3ne Are you using the Rich Text element?

If so, you can switch to the "Text" tab of the Rich Text element so that you can see the HTML. You should be able to either add classes (so that you can style them via Manage > Stylesheets in the top right of the builder) or add inline styles so that you can set the display to table or table-cell.

You can see an example of this here: https://oxygen-ql5yx23hh7k7.oxygen-demo.qsandbox.me/table-test/. If you want to log into the Sandbox site to see how the inline styles were added to the Rich Text element, the username and password are both demo.
