### ISSUE TITLE
When I open the editor, it shows up "Uncaught SyntaxError: Identifier 'mouseoverTimer'"

### ISSUE THREAD

**Issue by CriandoSites** [soflyy/oxygen-bugs-and-features#1877]
" Uncaught SyntaxError: Identifier 'mouseoverTimer' has already been declared on line #1 in https://meusistemax.com/home/?ct_builder=true&amp;ct_inner=true&amp;oxygen_iframe=true "

When I open the editor, it shows up

Yes I had tried all the steps

The screenshot: https://scontent.fpoa7-1.fna.fbcdn.net/v/t1.0-9/143100378_2811610192385464_5415574235273890210_n.jpg?_nc_cat=105&ccb=2&_nc_sid=825194&_nc_eui2=AeG2ndbeBsHf5aMqKPWrTFrE80WbFYzDyVLzRZsVjMPJUoCkE3HYlgFFDe7KBiEUAPuMvC23-w6fpP8-6u3gxrsB&_nc_ohc=BW0enCSZC5EAX_l9Vpx&_nc_ht=scontent.fpoa7-1.fna&oh=fb21a87aa2efd5ca23eb30fa02940f43&oe=6035538B

- OS: Windows
- Browser: Brave
- Oxygen Version:  3.6.1

**Comment by KittenCodes** [comment]
@CriandoSites Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support

**Comment by bellamystudio** [comment]
Not sure why this is closed, I'm getting it still on a page where I'm using the Tabs element and it's stopping me actually editing the page because it interrupts the rendering, so no content appears

SyntaxError: redeclaration of let mouseoverTimer on line #1 in /?ct_template=resource-template&ct_builder=true&ct_inner=true&oxygen_iframe=true line 2 > injectedScript

**Comment by Spellhammer** [comment]
@bellamystudio Please open a support ticket so that we can take a look at this for you: https://oxygenbuilder.com/support
