### ISSUE TITLE
Allow negation of dynamic data in conditions

### ISSUE THREAD

**Issue by dlovere** [soflyy/oxygen-bugs-and-features#1879]
It would be great to have the ability to negate a dynamic data condition. Currently the options are: 
`==, >=, <=, contains, is_blank, is_not_blank`

Use Case:
Creating different sidebars that will show based on a custom page taxonomy. 
Logic: Show "Global Sidebar" unless page has taxonomy term "Staff Portal"

Global sidebar div would have the following conditions: 
`[oxygen data="terms" taxonomy="page_types"] == Interior
  [oxygen data="terms" taxonomy="page_types"] != Staff Portal`

Staff portal sidebar would have the following conditions:
`[oxygen data="terms" taxonomy="page_types"] == Staff Portal
  [oxygen data="terms" taxonomy="page_types"] != Interior`

After reviewing Conditions.php, it looks like it may be as simple as: 
At line 176 modify the array to include the negation operator:
`array('==', '!=', '>=', '<=', 'contains', 'is_blank', 'is_not_blank'),`

At line 994 of conditions.php add this:
`} else if ($operator == "!=") {
			if ($executed_shortcode != $value) {
				return true;
			} else {
				return false;
			}`

Thank you!

**Comment by olithomp** [comment]
Silly question but: Where is "Conditions.php" ?

Im not sure if you could help me on this thread and if I am asking in the right place.. I want to populate dynamic data from custom post/field types created with the Metabox.io plugin.. is it possible? I am looking to customise the Oxygen builder "repeater" element without knowing what code to add where.?

Metabox supply a "custom post type code generator" if that is helpful..
https://metabox.io/post-type-generator/

Would be so GREATFUL to any support you can give!!
[ BECAUSE I have 14days to refund Metabox if I can't figure out how to make it compatible with Oxygen]

Huge Thanks,
O

**Comment by dlovere** [comment]
As of Oxygen 3.8 this is resolved. Thank you!
