### ISSUE TITLE
Post Migrate DB Pro Migration All templates lost data

### ISSUE THREAD

**Issue by jasperf** [soflyy/oxygen-bugs-and-features#2115]
I have Oxygen 3.7 on the WordPress 5.7. I migrated the database from the live website to staging to have staging on the latest live version. Did  a database backup as well. But still, now I have a site that seems to have only part of Oxygen templates left. I see no header menu anymore, no hero images, no footer. Only some products are still loaded.

Should Oxygen templates not just be restored? I mean, could be that images are not loading, but layouts should just run again should they not?

Here on the right live with all building and left a copy post migration with most blocks gone!

 blocks and left staging with most blocks/layers gone:

![Screen Shot 2021-04-21 at 2 40 21 PM](https://user-images.githubusercontent.com/344138/115515707-9a802d00-a2af-11eb-8415-eea99331d99e.png)

**Comment by KittenCodes** [comment]
@jasperf After migrating an Oxygen site, you must follow these steps:

1. Save your permalinks twice via Settings > Permalinks
2. Resign your shortcodes via Oxygen > Settings > Security
3. Regenerate your CSS cache via Oxygen > Settings > CSS Cache
4. Re-save your licence key via Oxygen > Settings > License so that your site can use one-click updates when a new version is available

You may also need to open each template in the admin area and click the Update button on the right-hand side but I've only found that to be required on a handful of sites.

If you have any caching plugins installed you will also need to clear the caches.

**Comment by jasperf** [comment]
I did 1,3,4 and skipped 2 as I had no signed shortcodes. No change and all still very broken. Turning off WP Rocket cache did not help either. I mean I got more back, but most styling is still gone. Header menu is still all broken.

**Comment by jasperf** [comment]
Saving pages in Oxygen template and savin default templates does seem to help now. Sure is a lot of work to it all to work again. Working on it all still. Also miss images but will need to clone the media directory still .

**Comment by KittenCodes** [comment]
> I did 1,3,4 and skipped 2 as I had no signed shortcodes.

The steps must be performed in order. You have shortcodes on your site - that's how Oxygen's designs are stored. Or, do you mean that shortcode signing is disabled?

**Comment by jasperf** [comment]
Shortcode signing had not been turned on. Realize we should on production at least so will do that soon now. But as copy had the unsigned version I did not have to resign I would think @KittenCodes ?

**Comment by KittenCodes** [comment]
@jasperf That's correct. If it was turned off, you shouldn't need to resign.

If you're still having problems, please open a support ticket and send us information on both sites (live and staging) so that we can take a look: https://oxygenbuilder.com/support.
