### ISSUE TITLE
CSS stylesheet vanished, can't edit nor delete it anymore but it's still loaded on frontend 

### ISSUE THREAD

**Issue by runechronos** [soflyy/oxygen-bugs-and-features#2155]
Hy,

I'm using Oxygen Builder 3.8 alpha, I don't get why, but i created a stylesheet via "**add stylesheet**" inside the builder, i put some CSS in it. And the Stylesheet is not showing inside the **stylesheets section**. So i can't edit nor remove it, yet it is still loaded on the frontend. Very troublesome, I don't get what happened, and it only happened once. I have created other stylesheets the same way to test and it has a normal behaviour now.

The problem is i'm stuck with a "**ghost**" stylesheet. I need to delete it but i dont know how to access it somewhere, in which hard file can i delete this ? (as i suppose it is generated automatically by Oxygen when rendering).

Thanks for your help, really strange bug. 1st time I have this one, I'm using Oxygen since 2018.

**Comment by Spellhammer** [comment]
We can't reproduce based on the information provided here, but I would like to investigate.

Please submit a ticket with login credentials via https://oxygenbuilder.com/support. Note that we can't actually provide support for your site since you're running the alpha, but we'll take a look to try to identify what has happened and make sure it's not a new bug.
