### ISSUE TITLE
Section height bug <maybe>

### ISSUE THREAD

**Issue by goodonline** [soflyy/oxygen-bugs-and-features#2207]
**Describe the bug**
I have a section that I cannot set the height in. More accurately, It sets within the Oxygen editor, but not when previewed in the browser (lastest version of chrome). I have a class attached to the section. When previewed in the browser, the class does not appear to stick

Issue happening on Home page, in the (first) 'Section Menu Divider'

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
https://wordpress-588022-1953334.cloudwaysapps.com/

I am somewhat new to Oxygen, so this could very well be a user error. 
Hope this information is helpful.

Thank you!!

**Comment by Spellhammer** [comment]
If it's this section: https://d.pr/i/Pf1wU1 - the height property on the id styles is missing the unit. This means it's using the 200px height from the .tcg-section-setup class instead. This is working as expected, but you can't make it taller or shorter than 200px because it has a min-height and max-height of 200px.

The missing unit is possibly a bug, but we'll need to actually log in to see why it's happening.

If you'd like further assistance with this, please submit a ticket at https://oxygenbuilder.com/support with login credentials so we can take a closer look.
