### ISSUE TITLE
PODS

### ISSUE THREAD

**Issue by wshill** [soflyy/oxygen-bugs-and-features#222]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by wshill** [comment]
Miss-post

**Comment by tobytraylor** [comment]
Does the closing of this mean that PODS support has been added or is underway.

**Comment by SeeJaneB** [comment]
> Does the closing of this mean that PODS support has been added or is underway.

@tobytraylor It must have been closed because it is a duplicate. Make sure you have voted for this over on Post #478 [https://github.com/soflyy/oxygen-bugs-and-features/issues/478](https://github.com/soflyy/oxygen-bugs-and-features/issues/478) 

Would be great to have PODS fully integrated for those of us who can't afford ACF Pro.
