### ISSUE TITLE
DONE: Add HTML tag changer in Repeater

### ISSUE THREAD

**Issue by mrogaar** [soflyy/oxygen-bugs-and-features#2353]
**What I would like to see:**
Change HTML tag of the repeater helper like in divs.

**What are the use cases for this feature?**
I.e: Make a ul list

**Comment by kindness-awareness** [comment]
I would like to voice the opinion of Uppsala Municipality (Sweden) that this problem is a direct hindrance for us to comply with international accessibility standards (https://www.w3.org/TR/WCAG21/, https://www.w3.org/WAI/WCAG21/Techniques/html/H97.html), which the European Union specifically demands that we must follow (https://digital-strategy.ec.europa.eu/en/policies/web-accessibility).

For instance, we want to use the repeater to create structures of these types:

* &lt;nav&gt;   &lt;div&gt;… &lt;div&gt;… &lt;div&gt;…   &lt;/nav&gt;
* &lt;ul&gt;  &lt;li&gt;… &lt;li&gt;… &lt;li&gt;…   &lt;/ul&gt;

But we can’t because the parent element tags (&lt;nav&gt; and &lt;ul&gt; in these examples) must be &lt;div&gt; and this directly breaks international accessibility standards that are required laws put upon every single governing body/institution within EU and whole a lot of other organs in the world.

**Comment by ZacharyElkins** [comment]
No update? This would be helpful

**Comment by Vyyt02** [comment]
This is super-impotant for accessibility.

**Comment by gslwebsolutions** [comment]
Long overdue

**Comment by Spellhammer** [comment]
Implemented in 4.6 beta 1.
