### ISSUE TITLE
Metabox Dynamic Data From Group Fields Doesn't Work

### ISSUE THREAD

**Issue by kevingeary** [soflyy/oxygen-bugs-and-features#2408]
**Describe the bug**

Dynamic data works for Metabox fields that are NOT in a group. But, when the fields are put in a group, the Dynamic Data functionality no longer works. **This also makes it impossible to query cloneable fields with a repeater because this functionality relies on the cloneable fields being inside a Metabox group.**

**Steps to reproduce the behavior:**

1. Add a metabox custom field group.
2. Add items to the group, like a text box.
3. Fill out the fields in the group on a post and publish.
4. Create an Oxygen template targeting posts and try to pull dynamic data from those fields onto the template.

OR

1. Add a metabox custom field group.
2. Add a text box to the group and make it cloneable.
3. Fill out the field in the group on a post, with additional clones, and publish.
4. Create an Oxygen template targeting posts
5. Add a repeater and select to query from a Metabox group.
6. Choose the group with the cloned fields. The repeater fails to query divs for each cloned item.

**Comment by KittenCodes** [comment]
@kevingeary We weren't able to reproduce using the first set of steps.

As for the second set of steps, we have made a change in the Beta to ensure that Oxygen only allows Meta Box Groups to be used as the Repeater data source if they're cloneable. This is because Oxygen's Repeater works with Cloneable Groups, not Cloneable fields inside the Groups.
