### ISSUE TITLE
Metabox cannot output its shortcode in Oxygen shortcode block for Checkbox List type of field

### ISSUE THREAD

**Issue by jevgen** [soflyy/oxygen-bugs-and-features#2446]
If you add Metabox shortcode to Oxy shortcode block for Checkbox List type of data, it returns nothing. 

1. Install Metabox and add Field Group of Checkbox List type
2. Create Custom Post type and assign Field Group to this Custom Post type
3. Create Oxygen template for this Custom Post type
4. Add Shortcode Block with Metabox shortcode to display that field 
5. See nothing happens

If you try to display values from that Metabox field with [standard Metabox helper function](https://docs.metabox.io/fields/checkbox-list/) with foreach() operator, you are getting error:
' Warning: Invalid argument supplied for foreach() in /nas/content/live/bwddevdev/wp-content/plugins/oxygen/component-framework/components/classes/code-block.class.php(115) : eval()'d code on line 4'

<img width="1523" alt="Screenshot 2021-10-05 at 07 12 51" src="https://user-images.githubusercontent.com/255431/135959194-83a42e63-2c7f-434b-a74b-bd7a1a4147c9.png">
<img width="1102" alt="Screenshot 2021-10-05 at 07 00 39" src="https://user-images.githubusercontent.com/255431/135959239-4c0eaacb-6402-46ee-a5f5-c6255907caf2.png">

**Comment by jevgen** [comment]
Current workaround is to use MB Views Twig templating capability to offset code execution for Checkbox List output of labels and values to Metabox side, since [mbv name="your-view-id"] shortcode is rendered by Oxygen. But it would be much nicer, if Oxy could do this itself. 

<img width="1203" alt="Screenshot 2021-10-05 at 08 18 49" src="https://user-images.githubusercontent.com/255431/135964585-caa40d9b-0a9b-4667-84f8-38497868b0b6.png">

**Comment by KittenCodes** [comment]
@jevgen I've not been able to replicate this on a clean Sandbox site. Here's the result if I add the Meta Box shortcode to display the font-end fields - you can see the Checkbox List at the bottom: http://lucky-elephant.w6.wpsandbox.pro/about-me/.

Are you able to replicate this on our [Sandbox site](https://oxygenbuilder.com/try)? You'd need to install Oxygen v3.9 Beta 1 to add Meta Box integration to the Sandbox site.

If it's only occurring on your site, please open a support ticket so that we can take a look at your site: https://oxygenbuilder.com/support.

**Comment by jevgen** [comment]
This is probably hosting security prohibits that kind of using eval() in expressions. WPEngine in my case.
