### ISSUE TITLE
|-OR- artifact using Product Cart Button on Mobile Views

### ISSUE THREAD

**Issue by switchupcb** [soflyy/oxygen-bugs-and-features#2575]
**Describe the bug**
![Screenshot_20211213-050434_Chrome](https://user-images.githubusercontent.com/81384235/145868936-dafd199b-0b18-4cca-a14b-54a758620a77.jpg)

*Steps to reproduce the behavior:
1. Add a `Product Builder` and then a `Product Cart Button`.
2. Save the page.
3. Use a mobile phone to view that page (i.e Samsung, iPhone)

This does not occur using web-tools on any of the displays so I'm not sure which ID to `display: none`. The issue may also effect the button itself (as padding usually looks like this):
![image](https://user-images.githubusercontent.com/81384235/145869981-4092a4c8-6560-4a96-a3f9-62308fe9ebde.png)

**Comment by KittenCodes** [comment]
@switchupcb This is caused by a conflict with another plugin on the site. Please run a [plugin conflict test](https://pluginconflict.com/?plugin=Oxygen) to determine which plugin is causing it to occur.

If you need help hiding the OR text, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by KittenCodes** [comment]
In case anyone else comes across this:

​Please try adding the following CSS to a stylesheet in the top right of the builder to remove the "|-OR-" text:
​
```css​
#wc-stripe-payment-request-wrapper, #wc-stripe-payment-request-button-separator {
  display: none !important;
}
```
