### ISSUE TITLE
Toggle box initial state selection not working

### ISSUE THREAD

**Issue by mrsharding2011** [soflyy/oxygen-bugs-and-features#2663]
When editing a template in Oxygen and a toggle box is added from the Helpers section,  the 'Toggle Initial State' can't be selected. The options are unresponsive.

https://oxygen-qy2m2krasybkl.oxygen-demo.qsandbox.me

**Comment by KittenCodes** [comment]
@mrsharding2011 The option does work, but it doesn't go blue when it's clicked as a class is initially selected. However, you will see that there's a small outline around the option that is selected.

If you switch to the element ID instead of the class, you will see that the option does go blue to indicate that it's selected.
