### ISSUE TITLE
SVG image missing height and width

### ISSUE THREAD

**Issue by viniciusmartin** [soflyy/oxygen-bugs-and-features#2715]
When I add an SVG image, the height and width attributes don't show up on the frontend.

For Core Web Vitals it is an essential factor.

**Comment by KittenCodes** [comment]
@viniciusmartin How/where are you adding the SVG image, is it via the Image element?

Are you adding the width & height attributes via Advanced > Attributes?

**Comment by viniciusmartin** [comment]
@KittenCodes yes, I'm using the image element.

I entered the height only, in the image dimension field. The width I changed to automatic, to be proportional.

But when I insert a common image (PNG, JPG, etc), even with the same dimensions, it inserts the height and width values in the front-end.

**Comment by KittenCodes** [comment]
@viniciusmartin Please could you let me know what you're using to allow SVGs in WordPress? Is it the SafeSVG plugin?

**Comment by viniciusmartin** [comment]
@KittenCodes yes, that's it.

**Comment by KittenCodes** [comment]
@viniciusmartin Just checking that I understand - are you saying that the SVG image code contains width and height attributes? If that's the case, you'd need to copy the SVG code and place it inside a Code Block element, instead of uploading it via the Media Library.

Unfortunately, Oxygen cannot extract attributes from an SVG image added via an Image element.

One workaround would be to add the attributes manually, by clicking on the Image element and going to Advanced > Attributes.

If I've misunderstood the issue, please could you explain further?

**Comment by viniciusmartin** [comment]
That's right.

No problem, I'll include the height and width attributes as per your orientation.

Thanks!
