### ISSUE TITLE
EasyPosts displays a single generic "Blog" entry instead of actual posts

### ISSUE THREAD

**Issue by sophodoros** [soflyy/oxygen-bugs-and-features#2735]
When I put an EasyPosts element on the website's main page, all of the Preset options work correctly. However, when I create a seperate page titled "Blog" and add an EasyPosts element to that page, the only Preset options that work are the ones with a "CSS Grid" prefix in the name. All the other Preset options display a single generic "Blog" entry instead of any actual posts. 

Sandbox link: https://oxygen-qhkv4q2yyhqkl.oxygen-demo.qsandbox.me/blog/

I've installed the FakerPress plugin to generate some random posts. Otherwise, the Sandbox is a standard Atomic installation.

**Comment by KittenCodes** [comment]
@sophodoros 

If you're using the Easy Posts element on a page (and not in an archive), then you need to click on the Easy Posts element, set the query to Custom, and then select the appropriate post type. I've done this for you on the Sandbox site.

Alternatively, if you assign the Blog page as the Posts page via Settings > Reading in the WordPress admin area, then you need to render it using a template instead. You can create a template via Oxygen > Templates, and you need to assign it to Other > Blog Posts Index. You may need to give the template a higher priority than other archive templates on your site. When adding an Easy Posts (or Repeater) element to a template, you need to set the query to Default instead of Custom.

I hope this helps!

**Comment by sophodoros** [comment]
The solution you provided in the 1st paragraph fixed the issue. Many thanks!

**Comment by KittenCodes** [comment]
Thanks @sophodoros. I've updated our documentation.
