### ISSUE TITLE
Rellax.js library ReferenceError

### ISSUE THREAD

**Issue by highorbit-io** [soflyy/oxygen-bugs-and-features#2773]
**Describe the bug**

Followed this YT video: https://www.youtube.com/watch?v=nonR6GvG278

Unlike in the video, any editor page with this Code Block throws a "ReferenceError" 

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**

https://oxygen-qlr83zg6kk4kl.oxygen-demo.qsandbox.me/wp-admin/index.php

Page = "RELLAX" > Edit with Oxygen

Here's my Fakebok topic (3rd of 3 times asking about this same issue) showing a screen cap: https://www.facebook.com/groups/1626639680763454/posts/4871065702987486/

**Comment by KittenCodes** [comment]
@highorbit-io 

The error occurs because files in the PHP & HTML tab of Oxygen's Code Block aren't loaded in the builder. To prevent the error from occurring, you can load the JS file using the following code in the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin:

```php
wp_enqueue_script( 'rellax', 'https://cdnjs.cloudflare.com/ajax/libs/rellax/1.12.1/rellax.min.js');
```

I've done this on the Sandbox site and the error no longer occurs.

I hope this helps!

**Comment by highorbit-io** [comment]
Works better thanks. Please consider commenting this in that YT video, quite a few people had the same issue with no response from the author. Otherwise the video isn't really much of a resource.
