### ISSUE TITLE
Accordion(composite elements ) doesn't work -It's missing a few dots before class names in js code.

### ISSUE THREAD

**Issue by vasjanovak** [soflyy/oxygen-bugs-and-features#2786]
Oxygen 3.9

The accordion element from composite elements is missing a few dots before class names inside the javascript block.

Link to sandbox site isn't possible because sandbox doesn't have composite elements.

1. Go to page or template
2. Add a new section
3. Add accordion element
4. Try accordion on the front end - it doesn't work
5. In the backend, under the accordion code tab, go to javascript code
6. Check class names on lines 16, 17,  22, 23 - they are missing dots before the class names

![2022-03-16](https://user-images.githubusercontent.com/8231603/158495284-c27fbbbf-c130-4f84-a770-de673c897e91.jpg)

**Comment by Spellhammer** [comment]
Thanks for the report.

The classList.toggle() method doesn't require the period, because classList is a DOMTokenList collection of the class attributes of the element - a period would be invalid here.

If the Accordion isn't working for you, this is not the reason.

Please submit a support ticket at https://oxygenbuilder.com/support and we'll be glad to investigate further.
