### ISSUE TITLE
Site Migration Bug (Shortcode Signing)

### ISSUE THREAD

**Issue by switchupcb** [soflyy/oxygen-bugs-and-features#2793]
**Describe the bug**
Oxygen Builder presents issues to the end user during site migration (from say a stage). This issue is likely derived from shortcode signing. When it happens it's scary cause it looks like you lose everything (and existing issues are sparse).

**Steps to reproduce the behavior:**
1. Setup a staging website from an existing website using [How to Stage a WordPress Website](https://www.veerotech.net/kb/how-to-stage-a-wordpress-website-using-softaculous-in-cpanel/#Prerequisites_for_staging_a_website).
2. Modify templates and/or save them _(you may experience issues at this point; not guaranteed)_.
3. Migrate the website back to the existing website using partial changes _(simulates a manual copy of post_meta; used to preserve other tables in production)_.
4. Change URL in shortcodes from stage website URL to main website URL _(stored in wp_post_meta)_.
5. Resign shortcodes.
6. Certain templates may require direct modification ([COPYING INDIVIDUAL PAGE & TEMPLATE DESIGNS](https://oxygenbuilder.com/documentation/other/importing-exporting/)) even by following the steps in [Importing & Exporting](https://oxygenbuilder.com/documentation/other/importing-exporting/) due to random short code modification.
7. Resign shortcodes.

**6** may occur when you attempt to enable an already enabled Uncategorized Stylesheet folder (which is also disabled).

**The following issues solve the symptom.**
Issues with migration (https://github.com/soflyy/oxygen-bugs-and-features/issues/2115, https://github.com/soflyy/oxygen-bugs-and-features/issues/2213): Follow the [Importing & Exporting](https://oxygenbuilder.com/documentation/other/importing-exporting/) steps with the (Oxygen) CSS cache enabled.
Issues with the CSS Cache (https://github.com/soflyy/oxygen-bugs-and-features/issues/1426): `Universal CSS cache not generated` error occurs when the CSS cache is disabled. The Universal CSS cache is generated when the CSS cache is reenabled.

**Comment by KittenCodes** [comment]
@switchupcb What problems are you experiencing when doing this?

**Comment by switchupcb** [comment]
The shortcode is modified _(because step one changes the URL from the main URL to the stage URL)_. At 2. and 6, you may experience random deletion of elements in a template _(related to the shortcodes being modified)_.

On other hand, the Universal Cache cannot be regenerated without enabling the cache (on the stage). At some point, certain templates aren't rendered on the page (before/after shortcode signing) which makes it look like everything was deleted. **But it's not** (unless the modification was directly to the Shortcode).

What is the problem? Either the shortcodes being modified causes problems (even after the URL switch), or there needs to be documentation on how modifying shortcodes through the `wp_posts_meta` table works in relation to Oxygen.

**Comment by KittenCodes** [comment]
> The shortcode is modified (because step one changes the URL from the main URL to the stage URL). At 2. and 6, you may experience random deletion of elements in a template (related to the shortcodes being modified).

Any modification of Oxygen's shortcodes in the postmeta table can cause them to "disappear" as it invalidates their signature - you can learn more about shortcode signatures here: https://oxygenbuilder.com/documentation/other/security/.

Once the shortcodes for all appropriate post types have been resigned, the elements should continue to show as normal.

_After migrating an Oxygen site or changing the domain in your hosting, you must follow these steps in order:_

_1. Run a search and replace on the database to update the old domain to the new domain (the [Better Search Replace plugin](https://wordpress.org/plugins/better-search-replace/) is good for this). This isn't needed if you have used a migration plugin that runs a search and replace for you, such as [All In One Migration](https://wordpress.org/plugins/all-in-one-wp-migration/)
2. Save your permalinks twice via Settings > Permalinks
3. Resign your shortcodes via Oxygen > Settings > Security
4. Regenerate your CSS cache via Oxygen > Settings > CSS Cache
5. Re-save your licence key via Oxygen > Settings > License so that your site can use one-click updates when a new version is available_

_You may also need to open each template in the admin area and click the Update button on the right-hand side but I've only found that to be required on a handful of sites._

_If you have any caching plugins installed you will also need to clear the caches._

Once those steps have been followed, your content should display as expected.

> On other hand, the Universal Cache cannot be regenerated without enabling the cache (on the stage)

Yes, that's correct. You need to enable Oxygen's CSS caching to be able to regenerate the CSS cache.
