### ISSUE TITLE
Changes made with Oxygen Gutenberg Integration missing in the builder

### ISSUE THREAD

**Issue by ectu** [soflyy/oxygen-bugs-and-features#2949]
[https://oxygen-q8mnv3vj95nml.oxygen-demo.qsandbox.me](url)

Add text (or change image) with Gutenberg and save > will apply on frontend.
Open page with builder > old / original settings are loaded > e.g. text / pictures missing because of "old" url.

**Comment by maltmann-muc** [comment]
That's by design.
Oxygen Gutenberg Integration allows you to design blocks to be used in Gutenberg. 
The content you provide in Oxygen is just meant to be a predefined default content (text, images, ...), being copied to Gutenberg.
When editing the block in Gutenberg, the modified content is stored in Gutenberg, not in the Oxygen block.

Another perspective:
You might want to use a block on different pages with different content. 
That wouldn't work if the content changes would be synchronized back to Oxygen.

**Comment by ectu** [comment]
Hi

Thanks for the explanation.

Beste Grüsse
Dan
