### ISSUE TITLE
Oxygen is adding '-1' to manually created div id's 

### ISSUE THREAD

**Issue by jessebrightman** [soflyy/oxygen-bugs-and-features#2965]
Oxygen is adding '-1' to manually created div id's.  While creating div's in a code block for the purpose of adding dynamic anchor links, a '-1' is bring added automatically.  This is getting in the way of dynamically creating a link tag and a corresponding anchor id below.  

**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by jessebrightman** [comment]
I have dug into this and it is a result of the repeater field expecting to use blocks from the builder ( and repeat them ) and having to create unique ID's. for each  This is a good feature except when creating Code Blocks in the repeater that use dynamically created ID's in them ( best practice, I know how to code and don't need anything to do it for me ).  Unfortunately, the system tries to do this for me and ends up getting in my way instead and results in a poor design.  Of course, there are ugly hacks to fix this but this situation technically should not exist in the first place.  Thank you.

**Comment by mirkoschubert** [comment]
I have the same issue since Oxygen 4.0 was published. I guess 4.0 added the incremental values behind every ID within a repeater and this is actually a good thing. But if you're trying to use dynamically generated IDs this issue occurs.

I for myself used the slug of every entry as an identifier for anchors:

```
<span id="<? echo get_post_field('post_name'); ?>"></span>
```
You can actually use the old `name` attribute to fix this for the moment:
```
<a name="<? echo get_post_field('post_name'); ?>"></a>
```
But this isn't the best way since the `name` attribute is actually deprecated in HTML5 and you rely just on the good-will of the browser developers.

The best way to fix it would be to give us an **official way** to create dynamic IDs, such as:

* Oxygen could allow to set dynamic data directly to the ID fields of every element.
* Oxygen could allow to set additional IDs in the attribute section, with already allows dynamic data.

This would be a feature request for many, I think. For the moment Oxygen could also ignore incremental IDs in code blocks, but this would not fix the real issue here.
