### ISSUE TITLE
DECLINED: Oxygen Rebuild

### ISSUE THREAD

**Issue by SlmnAntnll** [soflyy/oxygen-bugs-and-features#2972]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*

I’m requesting a complete rebuild of Oxygen Builder using the newest technology possible. Designers and developers want, and need, a tool that will help them propel Wordpress website development into the future. 

Problem: 
Oxygen is currently built on old technology, it’s not the speediest loading builder, it has some annoying bugs that have been plaguing it for some time, and it’s missing various additions/features that users have been requesting for years.

Solution:
Rebuild Oxygen from the ground up using the most recent technology to future proof and continue the best Wordpress builder. Completely restructure the brand and pricing strategies as to ensure the ability to be able to meet market/community/support demand, to be able to advertise and market properly and to be able to continue funding the best Wordpress builder in the universe well into the future. 

Possible Rebrand ‘Oxygen Prime’

A product name that still uses the established name ‘Oxygen’ with the differentiator ‘Prime’ meaning of first and/or best quality 

It’s also a bit of a play on Optimus Prime who was a leader and advocate for two worlds to coexist. Which Oxygen creates—both Designers and Developers love working with Oxygen and it is a leader in this space. 

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*

Helping Developers and Designers propel Wordpress website development into the future.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by marcorubiol** [comment]
+

**Comment by PingDesign** [comment]
Yes, this is what we want! Oxygen is for developers/webflow designers and Breakdance is the Elementor/Divi non techie competitor.

**Comment by greenyboy** [comment]
+1 from me

**Comment by adrien-robert** [comment]
We want a site builder within WordPress for professionals! Look at the market of Webflow.
Please don't tell that the market is too small... Just keep providing the best tool for web developers to build professionals and the best possible websites within WordPress.

**Comment by gmitovsr** [comment]
I created an account just to reply to this and tell the devs i support this.

**Comment by avocadesign** [comment]
If this was to be done accessibility would also have to be front and centre. Accessible menus, accesibile modals, every aspect.

**Comment by richardroscoe** [comment]
Yes please! Happy to pay a subscription.

**Comment by boldfish** [comment]
Don't worry about backwards compatibility, all websites get rebuilt eventually, we'd like to do rebuilds using a better Oxygen, and not lose our clients to a competitor.

It's that, or do rewrites in a different builder.

**Comment by Raiondesign** [comment]
Yes this would be game changer! Let’s breathe Some new fresh oxygen!

**Comment by desupero** [comment]
I want it to actually work with Toolset which you said it would Louis!

**Comment by SuperfastWP** [comment]
I will happily pay a subscription to make this happen!

**Comment by Larotu** [comment]
+1 from me

**Comment by DCubin** [comment]
+1 for oxys future

**Comment by IKuipers1** [comment]
+1 from me

**Comment by xternalhunter** [comment]
+1 for sure. Largely been rebuilt in Breakdance, just take off the intentional throttling and add the extras back in

**Comment by elmichalos** [comment]
+ 1

**Comment by shibupandit** [comment]
+1 for oxy future

**Comment by stphnwlkr** [comment]
+1

My prediction is that the team will determine it is too hard to maintain two products and will begin to port Oxygen features over to the new builder. Version 1, when finally released, will be the replacement for Oxygen. Maybe they will take a page out of the Elementor playbook and release a free version for basic users and a paid version (subscription model instead of LTD) to add all the advanced features. In fact, they could probably sell two upper-tier versions — advanced and advanced developer.

**Comment by Web-Assist** [comment]
+1 - An annual subscription is welcome to keep Oxygen profitable, healthy and the devs motivated, after all, no profit, no  business.

**Comment by peterteszary** [comment]
Yesss..

**Comment by MrKubb** [comment]
Do it !

**Comment by JTabdesign** [comment]
Please do this! There is nothing close to Oxy on the market, there is a much larger market than you know

**Comment by Spellhammer** [comment]
Nice try, but rebuilding the entire product is not a feature request.

**Comment by frucci99** [comment]
+1

**Comment by emil-moldovan** [comment]
+1

**Comment by Jehu** [comment]
+1
If Oxygen is to have a future, a rewrite is inevitable!

**Comment by kevindewidt** [comment]
+1

**Comment by afed79** [comment]
Please reconsider. 
Prediction: Breakdance will not survive long. It's a better Oxygen or nothing.

**Comment by xternalhunter** [comment]
> Please reconsider. 
> 
> Prediction: Breakdance will not survive long. It's a better Oxygen or nothing. 

Alarming how many people starting to jump ship to Bricks, I love Oxy and ant it to work but facts are facts :(

**Comment by avocadesign** [comment]
> > Please reconsider.
> > Prediction: Breakdance will not survive long. It's a better Oxygen or nothing.
> 
> Alarming how many people starting to jump ship to Bricks, I love Oxy and want it to work but facts are facts :(

The pace of development at Bricks is staggering coming from Oxygen - 1.5 Beta is a massive upgrade and closes the gap on the essential missing features in pretty much all but:
- breakpoints 
- UI for conditional logic (you can now right conditions in code with the 1.5 version)

In a few months there won't be a functional gap and then Oxygen is gone for us. On it's current codebase and trajectory Oxygen can't compete on:
-  the loading speed of the builder
-  the loading speed of the front end code
- The multiuser editing capabilites - you can edit with multiple team members working on the site at once, I hadn't realised how much of a productivity killer that was for our agency until we got that capability back (we've had it in all previous systems like beaver builder and elementor)
- Simple things like being able to rename classes (imagine that...)
- A roadmap so you can trust development
- Bugs that get fixed in weeks not years

I'm grateful to Oxygen for making me a better developer and allowing us to design some amazing websites but Bricks has all that and a better faster interface that's more suited to being a Productive web developer as well as a good one.

**Comment by aQziany** [comment]
+1
