### ISSUE TITLE
Product description is not display in product list widgets

### ISSUE THREAD

**Issue by kamal87g** [soflyy/oxygen-bugs-and-features#3009]
Hi Team,
I found a bug in product list widgets, it does not show product description
https://oxygen-q9f3nbs7pj4c.oxygen-demo.qsandbox.me/sample-page/?ct_builder=true&ct_inner=true

Here is my live site also:  https://wordpress-787815-2689081.cloudwaysapps.com/index.php/xygenyx-formulas/
Also guide me how we can add dynamic content  for product description.

![image](https://user-images.githubusercontent.com/16898100/179809753-9b91e3ce-64ed-4d7b-94dc-47c347a28546.png)

**Comment by Spellhammer** [comment]
Hey @kamal87g 

It is a little confusing because we have controls for the description, but this is for the description of product archives and not individual products. If you create a template that uses a Products List element set to the default query, and apply that template to Product Category archives, you'll see that you can style the archive description using these controls.

WooCommerce doesn't show product descriptions in archives by default, but you can add that in using a simple code snippet: https://code.tutsplus.com/tutorials/woocommerce-adding-the-product-short-description-to-archive-pages--cms-25435.
