### ISSUE TITLE
MAKE THIS FULL PAGE EDITABLE IN GUTENBERG causes content to get lost.

### ISSUE THREAD

**Issue by GraphicFinesse** [soflyy/oxygen-bugs-and-features#3024]
If you disable "MAKE THIS FULL PAGE EDITABLE IN GUTENBERG" you loose all of the content changes. The problem is that if you make major changes to the page or decide to go backwards all your clients content will be lost.

Is this something you're aware of and is there a timeline to on a fix to the bug?

Sandbox Link
https://oxygen-qk6t2p3m278ml.oxygen-demo.qsandbox.me/wp-admin/post.php?post=44&action=edit

https://user-images.githubusercontent.com/110214052/182267980-a7d1ccda-81ed-4d5c-877e-fc85975e8522.mp4

**Comment by Spellhammer** [comment]
This is because the changed content is stored only on the page, and disabling "MAKE THIS FULL PAGE EDITABLE IN GUTENBERG" removes the content from the page. This isn't a bug, but I do consider it poor UX. I'll log an issue internally to add a warning or similar to ensure people don't do this accidentally.
