### ISSUE TITLE
Integrate with SendGrid API to email form data to domain account

### ISSUE THREAD

**Issue by ellamusina** [soflyy/oxygen-bugs-and-features#3116]
**Describe the feature you'd like to see included in Oxygen.**
*A clear, detailed description of the feature you're requesting.*
Would it be possible to add to Oxygen a feature. I noticed tilda editor offer that: https://help.tilda.cc/formssendgrid. We would like to have the same with oxygen. Can you have an option for the form to use SendGrid API?
I am noticing, I am not able to load sendgrid_php lib to the site. Oxygen is blocking the usage of the libs. I was not able to also load it anywhere inside Oxygen and use it. I think Oxygen is not allowing addition of libs in php. Or, please direct me to the subject how to use /load php libs to be used in forms edited by Oxygen.

Example usage (outside of wordpress): https://www.twilio.com/blog/email-contact-form-sendgrid-node-js

**What are the use cases for this feature?**
*e.g. Accessibility, e-commerce store that sells bicycles, etc.*
emailing the form: https://dev.1plus1cares.com/find-caregiver/

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*
https://help.tilda.cc/formssendgrid

**Comment by alexanderkladov** [comment]
Oxygen has nothing to do with WP mailers & it shouldn't try to.

Use something like [Post SMTP Mailer/Email Log](https://wordpress.org/plugins/post-smtp/) to force your site to use a proper mailing service, rather than the default PHP `mail()`. You can set it to anything you want, like SendGrid or even your web host's provided mail servers. With [Post SMTP Mailer/Email Log](https://wordpress.org/plugins/post-smtp/) you can even setup a backup mailer, so that you can be 100% sure you won't ever lose any mail, in case the primary mailer goes down (e.g. server issues or if you reach your plan limits).

[Integrating with SendGrid's SMTP API](https://docs.sendgrid.com/for-developers/sending-email/integrating-with-the-smtp-api):

Step 1: in SendGrid:
1. [Create an API Key](https://app.sendgrid.com/settings/api_keys) with at least “Mail” permissions.

Step 2: in [Post SMTP Mailer/Email Log](https://wordpress.org/plugins/post-smtp/)
1. Set *Outgoing Mail Server* to `smtp.sendgrid.net`.
1. Set *User name* to `apikey`.
1. Set *Password* to the *API key* generated in Step 1.
1. Set *Security* to `TLS` and *Mail Server Port* to `587`. If that doesn't work, try setting *Security* to `SSL` and *Mail Server Port* to `465` instead.

Keep in mind, that in order for any of the above to work properly, first you have to verify your domain ownership to SendGrid, otherwise you won't be able to send authenticated emails from your domain via SendGrid's service. Once verified, you will be able to send emails from WHATEVER@yourdomain.com address you want (even if that email address doesn't exist in on your mail server, which is very handy for transactional emails). But I am not going to go into details on how to do it, just google it, it's very straight forward. I am pretty sure [this is the article that describes what you need to do](https://docs.sendgrid.com/ui/account-and-settings/how-to-set-up-domain-authentication).

**Comment by Spellhammer** [comment]
Since we don't have our own forms, this is definitely out of scope at the moment. Marking it as declined.
