### ISSUE TITLE
Support for post-thumbnails not working when using Oxygen Builder with no theme 

### ISSUE THREAD

**Issue by coutableN** [soflyy/oxygen-bugs-and-features#3199]
Hi,

Support for post-thumbnails is not working when using Oxygen Builder with no active WordPress theme.

The post-thumbnails support is back when a default WP theme like twentytwentythree is active. 

Please, note that having a custom plugin to register functions can't help since add_theme_support() can't be called from within a plugin and MUST be called from a theme or child theme. I think this is exactly why this bug occurs. 

https://developer.wordpress.org/reference/functions/add_theme_support/ 

Just reporting,
Good day !!!

**Comment by Kpudlo** [comment]
Hello @coutableN, 

Thank you for the report. 

Oxygen supports featured images and uses the `add_theme_support('post-thumbnails');` in the core files. 

If you're having an issue with this, please provide some additional details regarding the problem you are having. If you can recreate it on a Sandbox site (https://oxygenbuilder.com/try),  send us a link to the Sandbox where the issue occurs. Otherwise, if you need to provide a link to the page or login credentials, please open a support ticket (https://oxygenbuilder.com/support), and we'll be glad to investigate further. 

For reference, you should be able to use `add_theme_support` in a custom snippet using the `after_theme_setup` action. : 

```php
function oxys_theme_supports() {
  add_theme_support( 'post-formats', array('video', 'audio' ) );
}

add_action( 'after_setup_theme', 'oxys_theme_supports' );
```
