### ISSUE TITLE
Border issue with transition effect from hover state to original state 

### ISSUE THREAD

**Issue by Iris-py** [soflyy/oxygen-bugs-and-features#3283]
Hi,

I want the border of the text-link appear on hover and disappear when hover si done with smooth transition on both state. I have a smooth transition on hover but not when hover is done and text-link get back to original state. 

I applyed transition on both original and hover state, and it seems to work fine for other type of change that border (for example background)

Below the link of sandbox site where i reproduced the issue:

https://oxygen-qvdw6yj94z2rl.oxygen-demo.qsandbox.org/fdgfdg/?ct_builder=true&ct_inner=true
https://oxygen-qvdw6yj94z2rl.oxygen-demo.qsandbox.org/fdgfdg/

**Comment by Kpudlo** [comment]
Hello @Iris-py, 

This isn't a bug in Oxygen. The issue is that you are transitioning from nothing/none to something else, which doesn't work. You would want to set your borders for the normal state to have something like 0px or a transparent color: https://d.pr/i/lqgrAs. 

This article may be helpful in understanding how to use CSS transitions: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions
