### ISSUE TITLE
Hide Main template when editing content

### ISSUE THREAD

**Issue by Brucekib** [soflyy/oxygen-bugs-and-features#3293]
An option to hide the main template when editing content or page/post templates. The header and footer don't load in the Oxygen editor but do load as normal for visitors to the website.

In a similar way, hide the inner content to be able to edit the header and footer only.

Maybe a button similar to 'open without the main template included' and 'open with the main template included' or a radio button 'include main template' etc.

I have sites where I'm unable to edit the page template unless I disable including the main template. That of course disables it for website visitors too. On other sites the content doesn't load but shows the rotating gear. After disabling the include main template the template loads without an issue.

Hope that all makes sense.

**Comment by Kpudlo** [comment]
Hi @Brucekib, 

> An option to hide the main template when editing content or page/post templates. The header and footer don't load in the Oxygen editor but do load as normal for visitors to the website.

You can hide any element in Oxygen using the eye icon in the Structure Pane (https://d.pr/i/5oNHJN). Or, you can select the Conditions button and set the In-Editor Behavior to "Always Hide" (https://d.pr/i/LTK1bY).

This will hide the element on that template and any other pages/templates that inherit it but will still show it on the front end.

You may also see another solution here: https://github.com/soflyy/oxygen-bugs-and-features/issues/2567#issuecomment-991686412.

Please note I am closing this as a duplicate since there is an existing request for this here: https://github.com/soflyy/oxygen-bugs-and-features/issues/2567. You may wish to upvote that feature request.

**Comment by Brucekib** [comment]
Hi @Kpudlo,

I've been using Oxygen for years and didn't know that this 'hidden' feature was possible.

Why not make it more visible to make it easier for anyone using Oxygen? 

Another great feature that Oxygen has that gives it a competitive edge over the competition that no one knows about. This should be on the list of reasons to buy Oxygen.

Please consider adding it as an option when editing a template.

Kind regards,
Bruce
