### ISSUE TITLE
Drag and drop builder (slow/crashes)

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#33]
I mentioned this during the alpha stage (all pages are similar in response)

https://www.useloom.com/share/5cee6a04180d41fab75894b2d9b942a9

I was told _"Thanks for sending that over. I'm able to replicate this slowness when dragging and dropping with a complex page design in Oxygen 2.2 Alpha 1. I'll get a report over to the developers so they can take a look to see why this is happening."_ but it seems to still exist in the 2.2 beta :)

Thank you

**Comment by Spellhammer** [comment]
Thanks for letting us know this is persisting for you. 

I was able to replicate this behavior by creating a new page and inserting the Hyperion full page design from the library two times. Once this was done, drag and drop was incredibly slow just like in your video. We applied a fix (which is included in 2.2 Beta) which corrected this behavior.

Since you're still experiencing the same issue, it's possible your circumstances are different somehow. Please shoot us a ticket at support@oxygenbuilder.com referencing this issue and including login credentials so that we can investigate a bit more.

**Comment by Spellhammer** [comment]
@Deanphillips Can you post your hosting specs?

**Comment by Spellhammer** [comment]
We found an issue with shortcode deobfuscation that I believe will correct this partially or wholly. The fix is slated for a future release (not 2.3).
