### ISSUE TITLE
Animation on scroll doesn't work, if a slider is in a section before.

### ISSUE THREAD

**Issue by rethschulte** [soflyy/oxygen-bugs-and-features#3378]
**Describe the bug**
*A clear and concise description of what the bug is.*
If i have a animation on scroll after a section where a slider is, the animation doesn't work.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

Sandboxlink:
Page with bug: https://oxygen-qd98s55h3rx8.oxygen-demo.qsandbox.org/sample-page/
Same Page without Slider: https://oxygen-qd98s55h3rx8.oxygen-demo.qsandbox.org/sample-page-2/

**To Reproduce**
Add a section with a slider.
Add a section after the slidersection and animate a div/img/text etc.

**Expected behavior**
*A clear and concise description of what you expected to happen.*
The animation on scroll should work properly. Fade/slide etc.

**Desktop (please complete the following information):**

- Windows
- Browser Chrome Firefox Opera
- Oxygen Version 4.6.2

**Comment by Kpudlo** [comment]
Hello, 

This issue should be fixed by going to Settings > Global Styles > Animate On Scroll in Oxygen and checking the "Refresh AOS On Page Load" setting. It should fix the issue.

If you still need help with this, please open a Support Ticket (https://oxygenbuilder.com/support) and provide a staging environment where we can see the problem. We'll be glad to assist further. If you can also include a link to this discussion in that ticket, that would be appreciated.
