### ISSUE TITLE
Advanced query not showing all results

### ISSUE THREAD

**Issue by nd0nd0** [soflyy/oxygen-bugs-and-features#3447]
**Describe the bug**
Querying for all woocommerce products assigned to a particular product-tag returns results of less than 1. That is to say, if a product only has 2 products assigned to it, the query will return 1 product.

**Backend**

![oxygen backend](https://github.com/soflyy/oxygen-bugs-and-features/assets/70109131/db42e68b-b6e3-4434-a85f-e777d7e8f5ef)

**Frontend**

![Frontend](https://github.com/soflyy/oxygen-bugs-and-features/assets/70109131/8e8d49dd-c850-4960-824f-39c546dfdfe7)

**Query screenshot**

![Query-screenshot](https://github.com/soflyy/oxygen-bugs-and-features/assets/70109131/456bdd68-2fc1-49e6-9bc6-6b1b4d343fb1)

Everything is implemented in the **sandbox** : [https://oxygen-qkrfaswn355vl.oxygen-demo.qsandbox.org/](https://oxygen-qkrfaswn355vl.oxygen-demo.qsandbox.org/)

Use the 'product-tag' [template](https://oxygen-qkrfaswn355vl.oxygen-demo.qsandbox.org/wp-admin/post.php?post=77&action=edit&qs_redir_cnt=1) to access the query implementation. 

I'd be grateful for any help you can give me to correct this problem.

Thank you!

**Comment by Kpudlo** [comment]
When using an Easy Posts/Repeater on a Taxonomy page, please use a default Query instead of a custom query.

If you need to customize the query, you must use an Advanced Query. To do this, after you've set up your parameters for the Advanced Query, add the following PHP functions to your site using your preferred [Code Snippets plugin](https://wordpress.org/plugins/search/code+snippets/).

```php
<?php
if(!function_exists('return_current_archive_taxonomy')) {
    function return_current_archive_taxonomy() {
        $current_taxonomy = get_queried_object()->taxonomy;
        return $current_taxonomy;
    }
}

if(!function_exists('return_current_archive_terms')) {
  function return_current_archive_terms() {
        $current_terms = get_queried_object()->term_id;
        return $current_terms;
    }
}
?>
```

Next, in the Advanced Query, add the Parameter "tax_query", select the value "array", and add the following values to the array (https://d.pr/i/g8CmuB):
- taxonomy = PHP Function Return value of "return_current_archive_taxonomy".
- field = "id"
- terms = PHP Function Return value of "return_current_archive_terms".

Closing this concern as it would be satisfied by https://github.com/soflyy/oxygen-bugs-and-features/issues/3138.
