### ISSUE TITLE
Repeater - Having issues with ACF Repeater

### ISSUE THREAD

**Issue by Deanphillips** [soflyy/oxygen-bugs-and-features#425]
**Describe the bug**

There's a few going on here, and I discovered them all inside of one test. That you can find here (however I'm going to do a write up for you below too)

https://www.loom.com/share/f911c6750f04409da380566742e08c35

1. The ACF Repeater fields keep disappearing when trying to use it. The options disappear in the back end. I have to redo everything to get them back, and then select them

2. On top of this, it's actually not displaying any of the content I have on a post, and everything is shown as broken (image broken)

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

I've replicated this here:

http://average-elephant.w6.wpsandbox.pro/2019/07/13/cupiditate-fuga-in-doloribus-quas-sint/

(another video of me doing this here: https://www.loom.com/share/029b77c9adeb4e4b86bc6add85f621dc)

**Comment by KittenCodes** [comment]
Hey @Deanphillips,

> On top of this, it's actually not displaying any of the content I have on a post, and everything is shown as broken

You need to modify your Image and Link withing the repeater field group to return the Image URL and Link URL, rather than the array. They will then display in the builder. You can see it working here: http://average-elephant.w6.wpsandbox.pro/2019/07/13/cupiditate-fuga-in-doloribus-quas-sint/.

> The ACF Repeater fields keep disappearing when trying to use it

I've updated the Sandbox site to 3.0 Alpha 2 and I'm not able to replicate the disappearing fields issue. Please let me know if it happens again for you in Alpha 2.
