### ISSUE TITLE
TypeError: startParent.hasClass is not a function

### ISSUE THREAD

**Issue by nikikinz** [soflyy/oxygen-bugs-and-features#43]
Whilst trying to move an element in the structure menu I got the following error in the header: TypeError: startParent.hasClass is not a function.

I'm using the Latest WordPress. 5.0.3,

Active plugins:

Classic editor
Oxygen: Oxygen 2.1.2

Linux Mint Cinnamon
Xampp Local host

![screenshot from 2019-02-01 19-53-44](https://user-images.githubusercontent.com/22677874/52124749-d7bf5c80-265c-11e9-9bfc-0d5353a918fc.png)

**Comment by Spellhammer** [comment]
Are you able to reliably reproduce this? If so, what are the steps? Just moving an element in the Structure Pane?

Can you reproduce it on a demo site at https://oxygenbuilder.com/try? 

If not, can you provide an All In One WP Migration backup (.wpress file) of the site so that we can do more testing?

**Comment by nikikinz** [comment]
The problem has not recurred and as it was during a learning process that I
came across the error, I'd be hard pressed to reproduce it. Thank you for
your reply and if I have any other "bugs" I'll be sure to try on the link
you gave me and try to reproduce the error.
