### ISSUE TITLE
(3.0 Alpha 2) - Background Featured image into section

### ISSUE THREAD

**Issue by vincenzo-72** [soflyy/oxygen-bugs-and-features#437]
** Describe the bug **
* I added a section inside it I set the background image featured image [oxygen data = 'featured_image'] in the builder is displayed while in the frontend you see all white. *

** You have tried all the steps on https://oxygenbuilder.com/documentation/tro troubleshooting / tro troubleshooting-guide /? **
*Yes*

** You are able to replicate the problem on a Sandbox installation at https://oxygenbuilder.com/try?**
*http://distinct-chicken.w6.wpsandbox.pro/2017/03/09/hello-world/*

** To reproduce **
1. Go to 'new template'
2. Click "add section"> "background"> ​​"Date"> "Post, featured image"
3. Save
4. See error in frontend

** Expected behavior **
* In the forntend you should see the background image *

** What actually happens **
* No images in the frontend, all white *

** ** Screenshots
* If applicable, add screenshots to help explain your problem. *

- Oxygen version [3.0 Alpha 2]

![error-background](https://user-images.githubusercontent.com/52895065/61993492-be77f580-b06c-11e9-9b48-0d338fac7a8d.jpg)

**Comment by Spellhammer** [comment]
Confirmed in 3.0.

**Comment by srikat** [comment]
Just tested and can confirm that the bug is still present in RC 1.

**Comment by rob** [comment]
I've been having this issue as well. Seems it's not limited to the featured image but some sort of shortcode issue?

Neither of the shortcodes presented below work in a section "Background Image" if the "**Oxygen Gutenberg RC 1**" plugin is activated, but if the plugin is **_deactivated_**, then _Shortcode 2_ works fine — but _Shortcode 1_ still doesn't work.

So that plugin is breaking Oxygen's ACF-related shortcodes somehow, or at least it appears to be. Not sure why the custom PHP functions one doesn't work either way.

@srikat, feel free to test?

---

**Shortcode 1**
```
[oxygen data='phpfunction' function='get_location_bg_url']
```

**Shortcode 2**
```
[oxygen data='custom_acf_image' settings_path='location_address']
```

**Comment by vincenzo-72** [comment]
> Appena testato e posso confermare che il bug è ancora presente in RC 1.

In the rc1 version it works fine for me.

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen.
