### ISSUE TITLE
Pods integration

### ISSUE THREAD

**Issue by muzaffarsiddiqui** [soflyy/oxygen-bugs-and-features#478]
Hi,
It would be great to have Pods Custom Fields fully integrated with Oxygen (the same way ACF is). Pods is awesome and free when needing custom post types, custom fields, relations between different post types and structured data in general.

Many thanks in advance for consideration.

**Comment by benhohner** [comment]
Ditto for Toolset

**Comment by AzzX** [comment]
Pods does it the Wordpress way so default Custom field support like what we have with ACF would work with not just pods, but many other plugins like cmb2 or just coding fields in yourself.  Taxonomy field support would be a bonus too.

**Comment by sightek** [comment]
Hi there,
I have recently looked into oxygen and I really like it, I want to move on from Eelementor but the pods support is what really stopping me.
I have contacted support asking about that and the answer I got was:

> Unfortunately, I'm not able to comment on future development plans for Oxygen. That said, if you would like to see PODs support in a future release, please add a vote to the feature request here: https://github.com/soflyy/oxygen-bugs-and-features/issues/478.
In the mean time, you can still retrieve data from PODs if you're comfortable writing a few lines of PHP in a Code Block when necessary.

I hope to see you support Pods soon, I'm putting my money where my mouth is and voting with my Dollar I'm going to buy the Oxygen Agency Package right now, I hope that helps.

Much appreciated.
Abdul.

**Comment by Caffeinedesign** [comment]
+1 for pods full support, oxygen doesn't recognise custom fields (for example gallery custom filed of pods) so it's impossible to make a simple gallery based on pods

it seems custom post types don't have problems


p.s. now that advanced custom fields has doubled his price i think this should have high priority.
pods is free, opensource, REALLY EXPANDABLE, with a HUGE documentation, and pods authors are very likely to help 

in an old post https://wordpress.org/support/topic/pods-integration-with-oxygen/ they said that if your team would cooperate they would be happy to support oxygen

**Comment by paparaboon** [comment]
Yeah I'd like to see Pods integration too please. Thanks in advance Team :-)

**Comment by alexfares** [comment]
+1 for pods full support.

**Comment by chryspear** [comment]
hopefully, this can get more likes. Massive support from me

**Comment by studiouau** [comment]
+1

**Comment by steferr** [comment]
+1 indeed

**Comment by pixel-spartan** [comment]
Ditto for integration. ACF subscription costs more than Oxygen after 12 months.

**Comment by mok2612** [comment]
+1

**Comment by shmaltz** [comment]
+1

**Comment by vegantraveler** [comment]
I just purchased Oxygen and would like to have full PODS integration too.

**Comment by balazsnemeth89** [comment]
Many people prefer Pods over ACF or Toolset (including me), it offers a great solution for freelancers, especially now that ACF Pro has introduced a yearly subscription model. For many developers with a lower budget Pods is the only way to go. It would be really nice to have Pods integration in Oxygen. Including that feature would be another very good reason to use Oxygen to build dynamic sites and be another step ahead of the competition.

**Comment by ccerr1** [comment]
I was looking for an alternative to ACF pro and ran into PODs which looks promising. I would love to have full integration into Oxygen.

**Comment by eric7186** [comment]
@jimtrue represents Pods and responded to the question of support in Oxygen Builder 1 year, 8 months ago. 
"Ah, Oxygen is another Builder. You are welcome to reach out to them and have them make contact with us to support our plugin (like they support ACF/ACF Pro and Toolset) in their Dynamic Data location. Since they didn’t integrate with us, they’re more than likely only dumping what is available directly in post-meta and it’s not being filtered by our API to return the correct display value you’re anticipating. It’s very doubtful our relationship fields will work in their builder without additional configuration by them.

I’m going to close this support ticket, because you will need to open a Feature/Enhancement request for us to support Oxygen Builder (https://github.com/pods-framework/pods/issues/new/choose), but since it’s a premium plugin, we won’t be able to do anything with that without cooperation from them."

**Comment by jimtrue** [comment]
That was in reference to Elementor Pro and their Dynamic Data option. @eric7186 Oxygen is another builder yes, but they didn't at least advertise they were supporting Pods directly and then not actually doing it ;)

**Comment by avb3** [comment]
Please PLEASE include full PODS intergration.

**Comment by SeeJaneB** [comment]
Just learned about PODs today. It looks amazing. I like that it is all in one, so you don't need both ACF and CPT UI, it is especially neat how the relationships work. And it's free. I'm trying to decide on my tool of choice now that I am doing more advanced sites and shying away from ACF due to the yearly subscription model. Would be great to get this integrated.

**Comment by Cerulis** [comment]
+1000

**Comment by johanneskopf** [comment]
+1

**Comment by scmrecordings** [comment]
+1 Would love to see this. Pods seems to be much more in the spirit of Oxygen (developer freedom) than ACF

**Comment by sc0ttkclark** [comment]
Heads up, we are working on direct integration with Oxygen from the Pods side!

Watch out for our Pods Page Builder Toolkit Add-On for Pods coming out in Oct/Nov -- it will be made available exclusively to our Friends of Pods (https://friends.pods.io).

**Comment by sc0ttkclark** [comment]
I show off how the add-on integration works near the end of my presentation for the Page Builder Summit here: https://summit.camp/presentations/scott-kingsley-clark-methods-to-deal-with-custom-fields-using-page-builders/ref/9/?campaign=SKC

**Comment by kalaio** [comment]
+1

**Comment by Caffeinedesign** [comment]
Are there news about pods integration? I ask both Aires, oxygen and pods wich @sc0ttkclark said in oct/nov would be out, but looking at pods Friends "rewards" couldn't see it

**Comment by sc0ttkclark** [comment]
@Caffeinedesign it came out on New Year's Eve :)

https://pods.io/2020/12/31/introducing-pods-pro-by-skcdev/

That post explains the reasons for separating the new add-ons out and how Friends still get discounts.

Oxygen integration is in the Page Builder Toolkit add-on.

**Comment by pv21design** [comment]
This integration should be a priority for the Oxygen team. It doesn't make sense to me, that we have to use a plugin that is more expensive than Oxygen itself. When we could have native integration with a free and very powerful plugin like PODS.

**Comment by jadigitalmarketing** [comment]
+1

**Comment by Caffeinedesign** [comment]
> @Caffeinedesign it came out on New Year's Eve :)
> 
> https://pods.io/2020/12/31/introducing-pods-pro-by-skcdev/
> 
> That post explains the reasons for separating the new add-ons out and how Friends still get discounts.
> 
> Oxygen integration is in the Page Builder Toolkit add-on.

I must Agree with pv21design, i think it's not a very good pricing method to put It in a bundle, and as a multibuilder support, for example i would like only oxy support Also cause elementor already supports pods, beaver builder already has a plugin wich adds support and if i don't get wrong divi added support for it too... Sò why pay for only that function more than oxygen builder wich Is a full site builder? I suggest you Also a modular pricing, somethink like "only oxy plugin" "only elementor" "only permalink" with low prices

Obviously Is Just a suggestion, you did It and you decide how to price It 😅

**Comment by GrantigeOma** [comment]
**I found a super simple workaround for using Pods with the gallery element!**

_Disclaimer: This workaround  requires a very minor change in the Oxygen plugin sourcecode. Although it is highly unprobable that this will cause anything to break at all, proceed at own risk and be aware that you have to change it again after an update._

Step 1:
Got to "Plugins" - > "Plugin-Editor" on the WP Dashboard and switch to "Oxygen" on the top right.

Step 2:
Locate the "gallery.class.php" file  under "component-framework" -> "components" -> "classes" in the right navigation pane

Step 3:
Search for the "get_ids_from_acf( $fieldname )" function.

Step 4:
change it from
```
function get_ids_from_acf($fieldname) {
        if (function_exists('get_field')) {

            $ids = "";

            $images = get_field($fieldname)
            if (is_array($images)){
                foreach($images as $image) {
                    $ids .= $image['id'].",";
                }
            }
            else {
                _e("No ACF gallery field data found", "oxygen");
            }

            return $ids;
        } 
        else {
            return "";
        }
    }
```
to
```
function get_ids_from_acf($fieldname) {
        if (function_exists('pods_field')) {

            $ids = "";

            $images = pods_field($fieldname);
            if (is_array($images)){
                foreach($images as $image) {
                    $ids .= $image['ID'].",";
                }
            }
            else {
                _e("No PODS gallery field data found", "oxygen");
            }

            return $ids;
        } 
        else {
            return "";
        }
    }
```
Essentially switching out the get_field() function with the pods_field() function and capitalizing "id".

Now you can use any Pods image field set to multiple uploads in the gallery element by selecting "ACF" and putting in your pods field name instead of the acf field name!

I hope someone can get a use out of this :)

I think this shows how easy it would be to get full Pods support into Oxygen, so please just do it. :)

**Comment by sc0ttkclark** [comment]
Sorry about the current pricing model for Pods Pro, it's not a per-add-on model right now -- it's a pack model where you get a whole set of add-ons for one set price. I'll explore selling them individually in the future.

As for bundling multiple page builder integrations in one add-on, that's actually a technical decision I made to simplify and bring together many of the same things that each builder needs access to from Pods. Think of it as an interface between any page builder, plus the custom integration for that page builder itself.

I'm also happy to review any Pods-specific code that Oxygen wants to implement on their side. I'm just trying to keep Pods alive (it's free) through my work in Pods Pro.

**Comment by XelaMo** [comment]
+1

**Comment by gdnwebmedia** [comment]
+1

**Comment by SeeJaneB** [comment]
Just want to remind everyone adding +1, that voting is done by clicking on the little smiley face on the original post and selecting the thumbs up emoji. That is how the Oxygen devs have said that they track the popularity of requests and prioritize them. To make sure your vote counts, you gotta do it the right way!

**Comment by nightgolfer** [comment]
I would also very much like to see native PODS integration, primarily because of the nice features of PODS, and the new ACF Pro pricing model.

**Comment by Spellhammer** [comment]
Marking this as closed/declined, considering @sc0ttkclark has released an integration already.

@sc0ttkclark If there are improvement opportunities for the Pods/Oxygen integration that require changes on our end, feel free to reach out to us directly and we'd be glad to work with you.

**Comment by d19dotca** [comment]
@Spellhammer - Unless I misunderstand what @sc0ttkclark had provided, that integration between Oxygen & Pods was only present with a paid version of Pods. It should be native in Oxygen as it is for Elementor for the free version of Pods. When using Elementor for example that already has integration with Pods, I am not forced to purchase a premium version of Pods, I can use the freely open-source version of Pods. The way it seems to be now, if I want to use Oxygen with Pods I am forced to purchase a premium version of Pods.

**Comment by sc0ttkclark** [comment]
Pods Pro is a set of additional add-one for Pods. Pods is still free. There are additional Elementor features I'm working on for Pods Pro too. Really expanding things across page builders this year is a goal of mine.

Supporting custom fields should be a first-priority thing for Oxygen and other page builders, Pods Pro just takes what they have and expands and improves it to make it easier to work with on a Pods-centric level.

I think having something in Oxygen that covers ACF, Pods, and other plugins would be smart for them. But I understand the cost of that development especially with a solution already available and in development for more functionality.

**Comment by d19dotca** [comment]
> Pods Pro is a set of additional add-ons for Pods. Pods is still free.

Am I mistaken then in thinking that the Oxygen integration for Pods was only for users who purchased the premium version of Pods (Pods Pro) and does not work for the free version alone?

**Comment by sc0ttkclark** [comment]
> Pods Pro is a set of additional add-ons for Pods.

The featured add-on of this set is a Page Builder Toolkit add-on that covers Oxygen. There's not a free version of this add-on available, unlike the Beaver Themer add-on for Pods which still has a free add-on.

**Comment by d19dotca** [comment]
So then I think my original point stands... right now in order to work well with Pods free, Oxygen still has no full support integration with it. The only way for someone to get that is to purchase the Pods Pro Page Builders add-on. This means - at least in my opinion - that this ticket should not be closed as it's a valid feature request that Oxygen doesn't yet have support for natively. It's a shame that Oxygen doesn't want to support the amazing open-source Pods project. :-(

**Comment by damienlee77** [comment]
> Marking this as closed/declined, considering @sc0ttkclark has released an integration already.
> 
> @sc0ttkclark If there are improvement opportunities for the Pods/Oxygen integration that require changes on our end, feel free to reach out to us directly and we'd be glad to work with you.

I'm confused why Oxygen is not supporting Pods but would rather defer to a separate paid add-on as the solution? Why was this enhancement declined. It's really not in Oxygens favor and leaves Oxygen behind in terms of Pods integration when compared with its competition.

**Comment by Caffeinedesign** [comment]
up, hoping it will be reopened, also cause is one of the oldest oxygen feature requests mad in this hub, i can't understand why it's declined cause there is a paid alternative...

**Comment by gdnwebmedia** [comment]
While we wait for Oxygen to support Pods natively, here is an article that was very helpful in integrating Pods and Oxygen today.   https://syncwin.com/knowledgebase/wordpress/oxygen/display-pods-custom-fields

Hope this helps.

**Comment by pixelshrink** [comment]
> 
> 
> up, hoping it will be reopened, also cause is one of the oldest oxygen feature requests mad in this hub, i can't understand why it's declined cause there is a paid alternative...

Ditto, please reopen this issue @Spellhammer.  Would be great to have native Oxygen support without having to pay for the premium Pods extension.

**Comment by nightgolfer** [comment]
I'm not holding my breath for this to be re-opened, as it seems Soffly doesn't want to step on any Pods toes because the paid Oxygen (and other builders) support plugin (and the Pods Pro bundle that contains it) is their only source of income (apart from donations, it seems). Solidarity.

@sc0ttkclark — have you given more thought to changing the way you've modelled the pricing of the plugin? I'm not sure if you're aware, but Oxygen runs on a Lifetime Deal model, meaning that most of us Oxygen devs are used to/expect/prefer LTD plugins whenever possible. 

Personally, I am very averse to subscription models, because I don't want to build something for my clients where they're dependent on my paying for licenses to make their site continue to run. I also don't want to push the subscription cost to the client and have to explain to them why the site I'm building for them comes with an additional yearly subscription price, of which I won't see a dime. Selling the site design/build price is hard enough as it is.

I do not use any other builders. I don't want a Pods plugin that contains code for Divi, Beaver, or any other builder than Oxygen. The whole point of Oxygen (for me) is super tight, minimal code. No bloat.

I think you should consider making a standalone Oxygen plugin, with a LTD. I've already gotten Pods to work as I need it to on my own, but I'd gladly pay money for a Pods + Oxygen plugin with a LTD to support the project. There is no chance that I will pay $119 each year for the convenience of having slightly better Pods integration with my preferred builder than I already made myself. There is nothing else in the Pro bundle that I need.

I know it's not very likely that you'll want to change your current pricing model, but at least please consider that many/most Oxygen devs will not accept that model (my personal opinion, feedback and comments appreciated!), and there could — very likely — be a better way to get more of us to give you money. Which surely is the end goal.

Just my 2¢. I would be very happy to hear your thoughts on the matter.

Thanks for your time.

**Comment by Caffeinedesign** [comment]
> I'm not holding my breath for this to be re-opened, as it seems Soffly doesn't want to step on any Pods toes because the paid Oxygen (and other builders) support plugin (and the Pods Pro bundle that contains it) is their only source of income (apart from donations, it seems). Solidarity.
> 
> @sc0ttkclark — have you given more thought to changing the way you've modelled the pricing of the plugin? I'm not sure if you're aware, but Oxygen runs on a Lifetime Deal model, meaning that most of us Oxygen devs are used to/expect/prefer LTD plugins whenever possible.
> 
> Personally, I am very averse to subscription models, because I don't want to build something for my clients where they're dependent on my paying for licenses to make their site continue to run. I also don't want to push the subscription cost to the client and have to explain to them why the site I'm building for them comes with an additional yearly subscription price, of which I won't see a dime. Selling the site design/build price is hard enough as it is.
> 
> I do not use any other builders. I don't want a Pods plugin that contains code for Divi, Beaver, or any other builder than Oxygen. The whole point of Oxygen (for me) is super tight, minimal code. No bloat.
> 
> I think you should consider making a standalone Oxygen plugin, with a LTD. I've already gotten Pods to work as I need it to on my own, but I'd gladly pay money for a Pods + Oxygen plugin with a LTD to support the project. There is no chance that I will pay $119 each year for the convenience of having slightly better Pods integration with my preferred builder than I already made myself. There is nothing else in the Pro bundle that I need.
> 
> I know it's not very likely that you'll want to change your current pricing model, but at least please consider that many/most Oxygen devs will not accept that model (my personal opinion, feedback and comments appreciated!), and there could — very likely — be a better way to get more of us to give you money. Which surely is the end goal.
> 
> Just my 2¢. I would be very happy to hear your thoughts on the matter.
> 
> Thanks for your time.


agree, but i can't understand the step on toes part...
Scott was the first suggesting oxygen team to support PODS, and other builders support PODS in a way or another, so doesn't make sense to completely avoid support, also cause this request was much before the plugin existed, was one of the oldest, and most required for a long time...

**Comment by sc0ttkclark** [comment]
We don't have LTD licenses for Pods Pro because of the big caveat that maintaining support for an integration with a third party plugin is a year round development process.

With that said, if someone is interested in a lifetime license of just the Pods Pro Page Builder Toolkit Add On, contact me from the Pods Pro site (? icon in the corner) and we can take it from there privately. I'm sure we can figure something out that works for any of you.

**Comment by jakethesmith** [comment]
> 
> 
> **I found a super simple workaround for using Pods with the gallery element!**
> 
> _Disclaimer: This workaround requires a very minor change in the Oxygen plugin sourcecode. Although it is highly unprobable that this will cause anything to break at all, proceed at own risk and be aware that you have to change it again after an update._
> 
> Step 1:
> Got to "Plugins" - > "Plugin-Editor" on the WP Dashboard and switch to "Oxygen" on the top right.
> 
> Step 2:
> Locate the "gallery.class.php" file under "component-framework" -> "components" -> "classes" in the right navigation pane
> 
> Step 3:
> Search for the "get_ids_from_acf( $fieldname )" function.
> 
> Step 4:
> change it from
> 
> ```
> function get_ids_from_acf($fieldname) {
>         if (function_exists('get_field')) {
> 
>             $ids = "";
> 
>             $images = get_field($fieldname)
>             if (is_array($images)){
>                 foreach($images as $image) {
>                     $ids .= $image['id'].",";
>                 }
>             }
>             else {
>                 _e("No ACF gallery field data found", "oxygen");
>             }
> 
>             return $ids;
>         } 
>         else {
>             return "";
>         }
>     }
> ```
> 
> to
> 
> ```
> function get_ids_from_acf($fieldname) {
>         if (function_exists('pods_field')) {
> 
>             $ids = "";
> 
>             $images = pods_field($fieldname);
>             if (is_array($images)){
>                 foreach($images as $image) {
>                     $ids .= $image['ID'].",";
>                 }
>             }
>             else {
>                 _e("No PODS gallery field data found", "oxygen");
>             }
> 
>             return $ids;
>         } 
>         else {
>             return "";
>         }
>     }
> ```
> 
> Essentially switching out the get_field() function with the pods_field() function and capitalizing "id".
> 
> Now you can use any Pods image field set to multiple uploads in the gallery element by selecting "ACF" and putting in your pods field name instead of the acf field name!
> 
> I hope someone can get a use out of this :)
> 
> I think this shows how easy it would be to get full Pods support into Oxygen, so please just do it. :)

You sir are a legend!

**Comment by GrantigeOma** [comment]
> > **I found a super simple workaround for using Pods with the gallery element!**
> > _Disclaimer: This workaround requires a very minor change in the Oxygen plugin sourcecode. Although it is highly unprobable that this will cause anything to break at all, proceed at own risk and be aware that you have to change it again after an update._
> > Step 1:
> > Got to "Plugins" - > "Plugin-Editor" on the WP Dashboard and switch to "Oxygen" on the top right.
> > Step 2:
> > Locate the "gallery.class.php" file under "component-framework" -> "components" -> "classes" in the right navigation pane
> > Step 3:
> > Search for the "get_ids_from_acf( $fieldname )" function.
> > Step 4:
> > change it from
> > ```
> > function get_ids_from_acf($fieldname) {
> >         if (function_exists('get_field')) {
> > 
> >             $ids = "";
> > 
> >             $images = get_field($fieldname)
> >             if (is_array($images)){
> >                 foreach($images as $image) {
> >                     $ids .= $image['id'].",";
> >                 }
> >             }
> >             else {
> >                 _e("No ACF gallery field data found", "oxygen");
> >             }
> > 
> >             return $ids;
> >         } 
> >         else {
> >             return "";
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > function get_ids_from_acf($fieldname) {
> >         if (function_exists('pods_field')) {
> > 
> >             $ids = "";
> > 
> >             $images = pods_field($fieldname);
> >             if (is_array($images)){
> >                 foreach($images as $image) {
> >                     $ids .= $image['ID'].",";
> >                 }
> >             }
> >             else {
> >                 _e("No PODS gallery field data found", "oxygen");
> >             }
> > 
> >             return $ids;
> >         } 
> >         else {
> >             return "";
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Essentially switching out the get_field() function with the pods_field() function and capitalizing "id".
> > Now you can use any Pods image field set to multiple uploads in the gallery element by selecting "ACF" and putting in your pods field name instead of the acf field name!
> > I hope someone can get a use out of this :)
> > I think this shows how easy it would be to get full Pods support into Oxygen, so please just do it. :)
> 
> You sir are a legend!

Thx :) 
I actually got it working within a small plugin / code snippet, so you don't need to change the source code.
I post it tomorrow if i find some time.

**Comment by nightgolfer** [comment]
> Thx :) I actually got it working within a small plugin / code snippet, so you don't need to change the source code. I post it tomorrow if i find some time.

Please do! That would be awesome 😃👌

**Comment by GrantigeOma** [comment]
Here you go - just paste into Code Snippets and activate. It does the same thing as my code before, but in reverse. It declares the "get_field" function and makes it behave like the original ACF function but with the "pods_field" function at its core. ACF must not be installed alongside Pods of course or things will break.

```
function change_key( $array, $old_key, $new_key ) {

    if( ! array_key_exists( $old_key, $array ) )
        return $array;

    $keys = array_keys( $array );
    $keys[ array_search( $old_key, $keys ) ] = $new_key;

    return array_combine( $keys, $array );
}

function get_field( $fieldname ) {

	if( ! function_exists( 'pods_field' ) )
	{
	echo "PODS is not installed correctly or there is a compatibility issue.";
	return "";
	}

	

	$pods_field_array = pods_field($fieldname);
	foreach ($pods_field_array as $key => $field)
	{
	$pods_field_array[$key] = change_key($pods_field_array[$key], "ID","id");
	}
	return $pods_field_array;
}
```

Glad i can help out :)

**Comment by GrantigeOma** [comment]
I also found a nice tutorial on [Syncwin](https://syncwin.com/tutorial/oxygen-builder-and-pods-integration/) on how to get a single image displayed from Pods.
There I learned you can actually use the name of the pod and append "._src.SIZE" to display a single image from pods.

You just have to choose "Meta / Custom Field" in the data Modal. Then search for / type in the name of the field e.g. "my_image". and then append "._src.SIZE"  e.g. "my_image._src.medium".

Works like a charm!

And just for completion, this is how you can get Bi-Directional Relationships to work:

1. Use a Repeater with the  "Advanced Query" option.
2. Add "post_type" with the slug of the wanted related post type as a value.
3. Add "meta_key" with the slug of the current post type. (Or choose "data" and select the dynamic "Post Type" on the bottom)
4. Add "meta_value" and click "data" to dynamically add "Post ID" from the bottom.

Now only the related posts of the current post are being queried in the repeater.

If something was unclear or does not work, let me know.

**Comment by soiloui** [comment]
Why this is marked as closed?

**Comment by MagnumChaos17** [comment]
> Here you go - just paste into Code Snippets and activate. It does the same thing as my code before, but in reverse. It declares the "get_field" function and makes it behave like the original ACF function but with the "pods_field" function at its core. ACF must not be installed alongside Pods of course or things will break.
> 

Your clever workaround was wrapped in a plugin by @vitorrloureiro

Oxygen Pods Gallery Workaround
https://github.com/vitorrloureiro/vrls-wa-oxygen-pods-gallery

Thank you, @GrantigeOma !

**Comment by SeeJaneB** [comment]
With all of the momentum going with Oxygen development right now, I'm still hopelessly hopeful that this feature request can be reopened and we can get possibly get some Pods integration natively on the Oxygen end. 

I did finally get around to playing with a test license of the Pods Pro plugin that Scott was kind enough to let me use, but I found that I still needed to use PHP for a lot of things anyway, and there really isn't any documentation for how to do anything beyond the basics that are quickly shown in a video. I really don't want to have to have an extra plugin installed on my site and really can't afford the pro plugin's annual fee at this point in my small freelancing business at the level I am at currently. I do support Pods annually with a small gift, as a "Friend of Pods" because I don't expect a complete hand out and I do want to support their further development, but it is not enough to get the pro plugin at a discount.

I have managed to get all of the functionality I needed on a client site as is, but future sites would be simpler with some native integration. As I said before, I am a fan of how Pods handles both the custom fields and post types, along with relationships all in one plugin without the need to install any add-ons. I feel that it really is a great plugin and worthy of getting some love from the Oxygen devs.

**Comment by SeeJaneB** [comment]
Let's bring our 87 thumbs-up votes from this request over to #2122 which has not been officially closed yet.

**Comment by SeeJaneB** [comment]
> i bought a license of acpt ui plugin on appsumo fot 79 euros lifetime, It Is the new kid on the block, but developer Is working fast, he already made bricks integrazioni and quite soon It should integrate oxygen

@Caffeinedesign curious what the name of the plugin is that you are now using?
