### ISSUE TITLE
Use HTTPS for images from placehold.it

### ISSUE THREAD

**Issue by KittenCodes** [soflyy/oxygen-bugs-and-features#483]
The placehold.it images in the editor currently load over HTTP, which breaks and/or causes warnings on sites using HTTPS.

**Comment by yankiara** [comment]
18 months now for a ten second fix...
Placeholders images won't show with Chrome, this is ridiculous.

**Comment by luisceladita** [comment]
Come on, this is so easy to fix!

**Comment by wpsumo** [comment]
Please fix other http issues such as on EDD url + icons in the builder.

**Comment by luisceladita** [comment]
Guys, if the asset you need is available on SSL, always use the https:// assets !

**Comment by linkp** [comment]
Or even better, don't specify the scheme, and let the browser select the one that is most appropriate.

e.g. //server/assets

It's academic at this point, though, as palcehold.it has had an expired Let's Encrypt certificate since Monday, March 29, 2021 at 4:21:55 PM, and their site redirects to placeholder.com where all the documentation indicates that https://via.placeholder.com/ is the appropriate base for their URLs.

**Comment by tilen-seliskar** [comment]
This is still an active issue??

**Comment by KittenCodes** [comment]
Corrected in v4 Beta 1: https://oxygenbuilder.com/2022/02/11/oxygen-4-0-beta-1-now-available/.

**Comment by uhlhosting** [comment]
It was about time!
