### ISSUE TITLE
DONE: Feature:: CSS copy from ID to class and reverse function

### ISSUE THREAD

**Issue by wpsumo** [soflyy/oxygen-bugs-and-features#567]
**Describe the feature you'd like to see included in Oxygen.**
Copy and paste style from one element to another. Multi-select and copy to more than one element.

Copy ID or Class style and paste ID or Class style.

**What are the use cases for this feature?**
Would save a lot of time while designing.

Alternative also add copy style from ID to class and vise versa.

**Examples of this feature or functionality.**
https://www.youtube.com/watch?v=9hXKqlzWsHY
https://www.youtube.com/watch?v=7ngwSY84GYc

**Comment by wplit** [comment]
The idea of classes is so you don't need this. You can just give the new element the same class as the last one and the same line of CSS will now apply to that element also. Copy and paste styling is in Elementor because they don't use custom classes. It's a bad way to do it though as it means more CSS instead of just reusing the existing CSS.

I agree about the copy from ID to class and reverse though, as that would be useful if you've accidentally styled with ID and then need to reuse the styling.

**Comment by alriksson** [comment]
> The idea of classes is so you don't need this. You can just give the new element the same class as the last one and the same line of CSS will now apply to that element also. Copy and paste styling is in Elementor because they don't use custom classes. It's a bad way to do it though as it means more CSS instead of just reusing the existing CSS.

Totally agree, don't know what I was thinking about here. Of course, used and seen this feature.

> I agree about the copy from ID to class and reverse though, as that would be useful if you've accidentally styled with ID and then need to reuse the styling.

Yes happens to me all the time and pretty annoying when you want to keep the code clean, and have to remove one by one styling in Id's and add it manually into the class.

**Comment by Borkent** [comment]
Totally agree, I am making all my sites in oxygen now and this issue keeps following me. Costing me loads of time.

Also because you often just click around and then find the way to do it right, decide to use a class instead, there you go, backtracking all edits to ID and trying to remember to put em right again in css. 

One forgotten setting on the id will overrule the class setting, id > class

Please add simple button! Not copy id settings to class but MOVE current settings from ID of current element to CLASS (a,b,c - choose a existing class or crewte new class) of current element. 

Please!

**Comment by KittenCodes** [comment]
This has been implemented.

**Comment by Borkent** [comment]
Reopened? Are we gonna implement MOVE instead of COPY... me hopes 😃
