### ISSUE TITLE
Custom Page Width not showing on front-end.

### ISSUE THREAD

**Issue by Guido81** [soflyy/oxygen-bugs-and-features#582]
**Describe the bug**
*A clear and concise description of what the bug is.*
If you change the Page Width under All Settings / Page Settings then it doesn't show on the front-end. All sections stay at 1120px.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
http://odd-cockroach.w5.wpsandbox.pro/sample-page/

**To Reproduce**
1. Go to 'All Settings / Page Settings -> Page width. Set a new page width, example 1440px'
2. Click on 'a section you created and go to All Styles / size and Spacing and keep Section Container Width on page-width. Check the back-end and front-end. Front-end will stay at 1120px. Now changes the All Styles / size and Spacing - Section Container Width to also 1440px, now it shows on the front-end as well.'

**Expected behavior**
*A clear and concise description of what you expected to happen.*
That the section container width automatically changes to the globally set page width.

**What actually happens**
*A clear and concise description of what happens instead of the expected behavior.*
It stays on 1120px even if you change the page width globally

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
- OS: [Windows]
 - Browser [Chrome]
 - Oxygen Version [3.0.1]

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by Martin-1** [comment]
+1

**Comment by KittenCodes** [comment]
Replicated in v3.1.

**Comment by Paciente8159** [comment]
Version 3.6 still has the same annoyance. This affects not only page width but other styles as well.
After some investigation I found that the universal.css stylesheet is being loaded after the templates and page styles and this makes the CSS rules overwrite the others. This can be fixed by inserting the universal style sheet before all other (quick and easy fix is to change file component-ini.php lines 1158 and 1159 and place them before the comment `// check if to load dynamic xlink or cached CSS files` @ line 1152). A better solution (I think) would be to use wordpress built in dependency to ensure all style sheets are loaded at the correct order.
Please fix this. Thanks.

**Comment by KittenCodes** [comment]
Fixed in 3.7 Beta 1: https://oxygenbuilder.com/2021/01/22/oxygen-3-7-beta-1-now-available/.
