### ISSUE TITLE
FlexBox - Vertical alignment of a div inside of a section does not work.

### ISSUE THREAD

**Issue by Flipback8** [soflyy/oxygen-bugs-and-features#596]
FlexBox - Vertical alignment of a div inside of a section does not work.

**Please Watch Videos**:

[Flexbox Part 1](https://www.loom.com/share/03441322ca454e49b94572e9981fb2d4)

[Flexbox Part 2](https://www.loom.com/share/34a7e3579acb4992b804ba02db75f5c7)

Manual CSS that works:
Display:flex;
align-items:center;
Justify-content:center;

**Comment by wplit** [comment]
From what I can see, this is working as expected. 

A section is a pre-made component, which is made up of a <section><div></div></section> where the inner divs have the class of 'ct-section-inner-wrap' and are used to wrap the content inside (otherwise everything would stretch to the edge of the viewport)

In your examples when you hand code, you're missing out that important markup, that's why you're getting different results.

When you're using the flex controls in Oxygen on a section, it necessarily makes this ct-section-inner-wrap div the flex container, not the <section> itself, this is in order to make the content inside become the flex-items. If it didn't do this, it wouldn't work for aligning content.

If you do need the CSS to be applied to the <section> itself, in order to have the 'ct-section-inner-wrap' inner div act as the flex item (and not the elements inside), then you can apply using custom CSS as you have in your second video.

But it has to work this way. Alternatively if you don't want the extra inner markup, you can just use a div inside of a section, then change the html tag to <section> and manually do your wraps. Then you can still use the UI to set the flex without writing CSS.

**Comment by Flipback8** [comment]
Why not just allow the user to add a container element like in Webflow? The Div trick is a reasonable solution. Thanks for the reply/

**Comment by swinggraphics** [comment]
The Section element has Horizontal Item Alignment controls for Child Element Layout set to stack vertically, which are rules applied to .ct-section-inner-wrap. We expect to be able to apply vertical alignment in the same way, but because the controls aren't in Primary, we go to Advanced. The Advanced rules are applied to the section itself, instead of the wrapper div. The confusion is natural. This is a frequent annoyance for me, too. It's weird that there aren't vertical alignment controls for sections unless horizontal alignment is selected, and even then it might not work as expected if you've given the Section a specific or minimum height. Please just give us a way of accessing the ct-section-inner-wrap without mucking around with additional selectors.

**Comment by elperroverde** [comment]
If you set the Section's height to a specific value, lets say N pixels or even 100 vh, it works as expected and the content is centered vertically, BUT if you set (as I believe its a best practise) a min-height instead of a fixed heigh then you get the behavior showed in the first videos, content is not centered vertically
