### ISSUE TITLE
Gravity Forms / Oxygen issue

### ISSUE THREAD

**Issue by ciaoweb** [soflyy/oxygen-bugs-and-features#641]
Hi, This is an issue I am having between Oxygen and Gravity Forms. It happened in another website as well. 
In Gravity Forms setting I have setup a submit button to display only when the user answer to a question the right way. When I do the test in GF preview it works but when the form is rendered by Oxygen in the front end the submit button show up anyway.
Ii Oxygen editor I have added the GF shorcode using the shortcode module.

This video shows the issue: 
https://ciaoweb.dubb.com/v/EgAqxC

I have 2 sites with the issue:
https://www.robertociccolella.com/#contact-me
https://www.digitalsolutions.wales/contact/

Any help greatly appreciated. 
Many Thanks
Roberto Ciccolella

PS. Sridhar Katakam in his reply to my FaceBook post was able to replicate the issue and also mentioned that using a number field in GF does not cause any issue. I had to use a generic text one line field to allow people to input also characters and not only numbers.

**Comment by KittenCodes** [comment]
@ciaoweb I'm having problems reproducing this. Please install Gravity Forms on one of our Sandbox sites, create a similar form and send us a link to the page where the submit button is incorrectly showing so that we can investigate.

You can create a Sandbox site here: https://oxygenbuilder.com/try/.
