### ISSUE TITLE
Oxygen 2.2 RC is causing scripts enqueued by my custom plugins to not load. 

### ISSUE THREAD

**Issue by brianyhearne** [soflyy/oxygen-bugs-and-features#67]
Oxygen 2.2 RC is causing scripts enqueued by my custom plugins to not load. The scripts are registered inside the plugin shortcodes so they only load when needed and not on all pages.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
2.2RC not available in sandbox

**Expected behavior**
Plugin scripts should load.

**What actually happens**
Plugin scripts don't load.

**Desktop (please complete the following information):**
- Mac OS
 - Chrome
 - 2.2 RC

Copy of my plugins available at your request

**Comment by mdorchain** [comment]
Scripts/Css are not loading when registered in wp_enqueue_scripts but enqueued in a shortcode before the output. Moving the enqueuing in wp_enqueue_scripts solves the issue. 

This potentially impacts any plugin providing shortcodes with on the fly enqueuing.

**Comment by louisreingold** [comment]
Isn't this a violation of the WP API?

https://codex.wordpress.org/Plugin_API/Action_Reference/wp_enqueue_scripts

> wp_enqueue_scripts is the proper hook to use when enqueuing items that are meant to appear on the front end.

You aren't supposed to call wp_enqueue_script or wp_enqueue_style outside of a function that is hooked to the wp_enqueue_scripts action.

> Scripts/Css are not loading when registered in wp_enqueue_scripts but enqueued in a shortcode before the output.

I don't understand. Please elaborate.

Are you saying that calling wp_enqueue_script( 'my-js', 'filename.js', false ); inside a shortcode handler function doesn't work? If so, that's a violation of the WP API. Or are you saying that calling add_action('wp_enqueue_scripts') inside a shortcode handler doesn't work? That is also incorrect use of the WP API. 

Or are you saying something else entirely?

Can you please attach a plugin (ideally a simple one) that exhibits this problem?

**Comment by louisreingold** [comment]
> The scripts are registered inside the plugin shortcodes so they only load when needed and not on all pages.

That is what <script> and <style> and <link> tags are for.

**Comment by mdorchain** [comment]
We're on the same page concerning the mandatory use of the wp_enqueue_scripts actions. However registered script can be loaded on demand to avoid being printed globally on every page.

Here is an illustration: https://gist.github.com/mathetos/c665f24cd7d8d8a1fbad63a8d5c9a741#file-better_shortcode-php

I'm also referring to Mike Jolley's article about it: https://mikejolley.com/2013/12/02/sensible-script-enqueuing-shortcodes/

I have seen this technique in many themes and plugins in the past. I don't think there is anything wrong with it since it's following WP rules for enqueuing and still allows for de-registering if necessary.

**Comment by louisreingold** [comment]
> We're on the same page concerning the mandatory use of the wp_enqueue_scripts actions.

Please elaborate. 

The .org docs says wp_enqueue_scripts is the proper hook to use when enqueuing items that are meant to appear on the front end.

But the examples you've linked to enqueue the scripts outside of that hook. 

Regardless, I'm tempted to take Mike Jolley's advice here even though it seems to go against the API docs, since I suspect Mike Jolley knows more about how WP works than most people. 

Can you attach an example plugin that exhibits the problem?

**Comment by louisreingold** [comment]
> Can you attach an example plugin that exhibits the problem?

Nevermind, https://gist.github.com/mathetos/c665f24cd7d8d8a1fbad63a8d5c9a741#file-better_shortcode-php is perfect, thank you.

**Comment by mdorchain** [comment]
The gist illustrates css enqueueing but the same principal applies to scripts with wp_register_script. 
We experienced the issue on Oxygen with scripts. I haven't checked if the css where also impacted.
Thank you Louis for stepping in btw.

**Comment by louisreingold** [comment]
I believe we've fixed this based on our own tests, but can't test every possible shortcode, so please test RC2 and confirm that we have indeed fixed this with your shortcodes.

https://oxygenbuilder.com/2019/02/15/oxygen-2-2-release-candidate-2-now-available/

**Comment by jmcbade** [comment]
At the request of the author of Advanced forms, it seems this issue is back for him in the latest version of O3.0.1

I have been trying to work with him to solve a styling issue where hidden field are showing up in the O3 builder view.  Yes the field could be "re-hidden"? with CSS but the field still takes up space in the layout creating challenged with the layout of form elements.

> I'm guessing that those plugins do not use the regular style enqueuing in WordPress and have opted to do it some other way. My plugin was doing it another way before but that was causing issues as ACF uses that for their styles.

Could you reach out to the Oxygen team with a reference to the Github issue I linked before (https://github.com/soflyy/oxygen-bugs-and-features/issues/67)? That issue seems to be the exact same as we are running into right now and they have been trying to fix it.
> 

Could this issue be revisited for the latest version of Oxygen please?

**Comment by KittenCodes** [comment]
@jmcbade 

> Could this issue be revisited for the latest version of Oxygen please?

If this is still an issue for you, please set up an example using Advanced Forms on our Sandbox site at https://oxygenbuilder.com/try/ and send the login to support@oxygenbuilder.com so that we can take a look.
