### ISSUE TITLE
DONE: copy or move css definitions to a new defined class

### ISSUE THREAD

**Issue by chapolote** [soflyy/oxygen-bugs-and-features#677]
**Describe the feature you'd like to see included in Oxygen.**
It would be very helpful to have an option, when I asign a new class to an element to copy all definitions I made for the initial div to this new class and reset the definitions for the div then.

**What are the use cases for this feature?**
Often I forget to add a class to an element before I make my own adjustments. If I need those adjustments for another element, the use of classes is obligatory. It's a waste of time to check all adjustments I made for the initial div and mirror them to the new class. Especially as long if there is the bug, that e.g. border values are not displayed well in the panel or the indicator for changed values is still on even though I reseted all values manually. This makes it difficult to find out definitions I made previously.

**Examples of this feature or functionality.**
*If another product has done it well, provide examples here.*

**Comment by Janik-Dev** [comment]
can't say how often that happend to me. this would save a lot of time!

**Comment by alexanderkladov** [comment]
100% agree. There has to be a way to copy-paste all custom "Advanced" settings to/from elements. That would be such a time saver!

There should also be a way to quickly reset each section too (or all Advanced settings at once). Right now you have to do it manually, which is a pain in the ass.

Divi has that feature & it's invaluable. They have it via a hidden right click menu, which would be perfect for Oxygen too, since there is no right click menu right now, when you click on elements, so there is room to expand. Or a "Copy CSS/Paste CSS" button could be added next to "Duplicate Component" button.

**Comment by KittenCodes** [comment]
It's now possible to copy styles to/from IDs and classes.
