### ISSUE TITLE
DONE: New options for responsive menu

### ISSUE THREAD

**Issue by marceli78** [soflyy/oxygen-bugs-and-features#7]
Responsive menu builder with few choices to pick from: fullscreen, offscreen and others with dropdown submenus available.

**Comment by muzaffarsiddiqui** [comment]
+1

**Comment by alpabuz** [comment]
+1

**Comment by Flipback8** [comment]
Please add retractable toggle submenus to the mobile experience. Expanded menus do not provide the best experience, especially when the subcategories are long.

**Comment by Martin-1** [comment]
+1

**Comment by uitecs** [comment]
+1 "Please add retractable toggle submenus to the mobile experience. Expanded menus do not provide the best experience, especially when the subcategories are long."

**Comment by adrien-robert** [comment]
+1

**Comment by sukycz** [comment]
+1 "I also lack this element"

**Comment by OLEXNY** [comment]
Same her. It's a necessity!

**Comment by alriksson** [comment]
+1

**Comment by greenyboy** [comment]
+1

**Comment by RenaudGagne** [comment]
+1

**Comment by macintoshee** [comment]
+1

**Comment by muzaffarsiddiqui** [comment]
+1

**Comment by Spellhammer** [comment]
The Pro Menu element introduced in Oxygen 3.2 Alpha 1 addresses this feature request.

**Comment by argy132** [comment]
Hello everyone,

I would like to recommend 3 suggestions, that I believe will improve more the UX design of Pro Menu for mobiles

As I noticed until now for the mobile mode, your menus have the function of "toggle" to expand the subcategories, it will be a great good option also if you can use the function of "slide", meaning that when user click the main menu instead of toggle the submenu, the menu will slide on the right or left side, you already have this code that you trigger the off-canvas menu, you can add a slide effect also as a breakpoint of the menu for certain pixels, check this example, where this company have implemented in Elementor, I believe if you can use it also, you improve more your amazing UX design of your Mobile Menu-> https://shop.namogo.com/elementor-extras/widgets/slide-menu/

Another good feature for mobile mode, will be to add tabs where we can display different menus ( check attached screenshot )
Example: - > 1) https://nimb.ws/Nq5mQ1
Live example website ( mobile view )-> https://www.asos.com/women/

A last suggestion is to display in mobile menu an icon or a PNG files of the categories in the main and sub menu, check this website from you mobile to have an idea, if you add this option I believe you will have the most comprehensive options for mobile web
Example: - > https://nimb.ws/Nn6TBI
Live example website ( mobile view ) -> https://www.asos.com/women/

Thank you
Best Regards
Tolis
