### ISSUE TITLE
Header builder columns

### ISSUE THREAD

**Issue by alFrame** [soflyy/oxygen-bugs-and-features#706]
**Describe the bug**
I file this as a bug because it's not a feature request.
In the header builder the columns are named rows

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
dna

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes.

**To Reproduce**
Create a header using the header builder and read the node names.

**Expected behavior**
Rows should be called rows, Columns should be called columns.

![image](https://user-images.githubusercontent.com/27587287/68532119-03712080-031a-11ea-948c-88fa113497d7.png)

**Comment by briandash2** [comment]
I’m not an expert in this, but I just watched a Flexbox tutorial today and I believe Flexbox is the reason for this. Each element is called a “row” and then you can choose to stack the “rows” horizontally or vertically. This makes it easier to make responsive layouts because sometimes you want elements to stack horizontally, sometimes you want them vertically (especially on smaller screens). Changing the name of the container from row to column in those instances would be more complicated. 

This is where I learned about Flexbox:
https://mastery.games/p/flexbox-zombies/

**Comment by Spellhammer** [comment]
These are labeled as areas of the "header row". Row left is the left part of the row, row center is the center part of the row, and row right is the right part of the row.
