### ISSUE TITLE
Cannot edit an empty text block

### ISSUE THREAD

**Issue by ghost** [soflyy/oxygen-bugs-and-features#710]
**Describe the bug**
*A clear and concise description of what the bug is.*

When emptying a text block, it is impossible to edit it after focusing out of it.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
*Yes*

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
*If yes, provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*

http://adventurous-owl.w6.wpsandbox.pro/sample-page/?ct_builder=true

**To Reproduce**

1. Create a text block
2. Delete the default text
3. Deselect the text block or create another one
4. Impossible to edit the empty text block

**Expected behavior**
*A clear and concise description of what you expected to happen.*

We should be able to edit the text block

**Comment by KittenCodes** [comment]
Replicated in 3.1.

**Comment by shoelaced** [comment]
Just want to add to this that it is impossible to edit text that is layered behind a transparent `<div>` (or any element), because you can't double click on it and there's no way to edit text from the sidebar. So it seems like having an off-screen way to edit the contents of a text block would fix a lot of problems, including the above one.

**Comment by KittenCodes** [comment]
A basic text editor has been added to the Properties pane in v3.8 Beta 1, so you can now edit empty text elements.
