### ISSUE TITLE
Copy & Paste Elements

### ISSUE THREAD

**Issue by KittenCodes** [soflyy/oxygen-bugs-and-features#715]
Posted on behalf of Michael:

I would like the ability to copy and paste elements (it could be layouts, sections, or columnns or divs etc) between and across pages, templates, blocks and reusable parts. Saving them in a library, for use later would be useful too.

Being forced to always save as a reusable part makes reusable parts an administrative nightmare for those who want to copy and paste a lot. But only want to save a few, since deleting them (even the editable ones) deletes all the pasted instances.

**Comment by Gibsonion** [comment]
There already is a library for this, but cutting and pasting directly without having to save first would be useful

**Comment by d-packs** [comment]
+1. I'm switching from elementor where I've been very happy about this feature. 

The use case is this: you want to reuse most of the effort you've spent on a feature but don't really want to have a 1:1 copy. So you copy-paste the feature and edit the things you need.

Reusable elements are not helpful here, because you can only edit them globally.

**Comment by miksulous** [comment]
+1.
Making multiple pages with same kind of contents would be easier with copy  & paste. Maybe somekind of clibboard system for this? And using reusable parts for this is not the best way. 

(And I have tested duplicating pages too. That doesn't help as I think the Repeaters stop working after this (bug?). Changing name for repeater helps (so not multiple repeaters with same name).

**Comment by Kpudlo** [comment]
Implemented in v4.0 and v4.1
