### ISSUE TITLE
Highly Dynamic Templates = Avalanche of 503 Errors.

### ISSUE THREAD

**Issue by perrelet** [soflyy/oxygen-bugs-and-features#826]
**Describe the bug**

When loading templates that contain lots of dynamic data content, I often get 503 service unavailable errors.
i.e The oxygen error dialog pops up with:

_Error occurred while rendering shortcode 503
Your server returned a 503 error for the request to ***._

Checking the console, the ajax calls are returning: _The server is temporarily busy, try again later!_

... which leaves the template text with **"no data for field"** and images / backgrounds **blank**.

---

I normally just switch the current post being previewed, cross my fingers and the dynamic data normally populates on the second attempt.

Things are somewhat more extreme however when you throw a multilingual platform such as WPML into the mix. I'm guessing this is because grabbing meta values takes longer as there's some additional logic WPML uses to ensure the correct meta is grabbed for the correct language...

In any event, on this particular site with WPML installed, when I go to edit templates that are rich in dynamic content, the **503 errors land like an avalanche**...

I presume oxygen is simply throwing out the AJAX requests without first checking how many have returned a response. Having a quick look at the js, it looks to me like oxygen is sending out these requests on a 100ms setTimeout cycle. If correct - **pretty please, we need better exchange control**.

Finally, on pages that are not templates, but are still built in oxygen. There's no way of reloading the dynamic data (as there isn't a select post preview option for these pages). As such, at the very least, a button that "reloads all dynamic data" would be helpful...

---

**Expected behavior**

Meta data appears in templates as expected.

**What actually happens**

"no data for field", "no data for field", "no data for field", "no data for field", etc.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Oxygen Version 3.1.1

**Comment by shoelaced** [comment]
I'm seeing this all over the place as well. It's gotten so bad that I can barely work on the site, specifically a page that has about 15 ACF fields.

**Comment by KittenCodes** [comment]
@perrelet @shoelaced 

Please send site login details and links to the appropriate templates to support@oxygenbuilder.com so that we can take a look at this for you.

**Comment by wpsumo** [comment]
@KittenCodes  +1 I have way more than 15 dynamic fields it crashes the whole server. As it hammering admin-ajax.php.

**Comment by shoelaced** [comment]
I still regularly have this problem as well, but if you click into all the text boxes as if to edit them, they load after you click out again, and regardless, it seems to save new changes fine. It's extremely annoying but since I can still get my work done I haven't made time to set up debugging sites for the Oxygen team.

**Comment by wpsumo** [comment]
@shoelaced That as well. But for me the builder is loading so slow and kill the server and I can sometimes not even edit some templates any more.

Happy it works for you, but once the dynamic data grows Oxygens code base can't handle it any more. We see several of themes and plugins rebuilding their code base and make it smarter, faster and update libraries. Oxygen haven't done much there, and it feels outdated and slow. We can't expect a Fiat to run as a Ferrari just because we put a Ferrari engine in it.

But hope to see Oxygen looking into this matter soon :)
