### ISSUE TITLE
Pro Menu Dropdown Animation Problems (3.2 RC1)

### ISSUE THREAD

**Issue by sfries79** [soflyy/oxygen-bugs-and-features#855]
When moving the pointer over a link and into the space of the appearing dropdown menu before the dropdown animation finishes the dropdown just disappears.

Tested in Firefox and Edge Chromium.

As a workaround I tried to disable the animation, which seems to be working in Oxygen, but just reverts to “fade up” on the page. My second idea was to set a faster animation duration, but I couldn’t find any option for that – shouldn’t there be one?

I hope this is somehow solvable, as it still feels a little broken.

**Comment by Spellhammer** [comment]
This is because we've added pointer-events: none to animating submenus. This was done to prevent the activation of the submenus & sub-submenus during animation when the path of animation intersects with the mouse cursor. Otherwise you end up with very strange results.

The submenu animations inherit their settings from Manage > Settings > Global Styles > Animate on Scroll. You can change the transition duration there.

**Comment by sfries79** [comment]
I’m not sure if I’m doing this right, but there is some strange behaviour when changing animate on scroll duration. Setting it to “0” doesn’t do anything (to the menu), setting it to any other value disables the animation. To be honest, I don’t get why this setting is even related to the animated menus, but the counterintuitive behaviour on changing it looks just strange.

Regarding the disappearing drop down menus, I don’t understand why this isn’t getting better when the animation is disabled. I need to move the pointer really slow for the menu to work and it feels just as if there is something wrong with it. Isn’t there a more robust way of implementing this? I never had a problem like this with the old menu.

**Comment by KittenCodes** [comment]
> When moving the pointer over a link and into the space of the appearing dropdown menu before the dropdown animation finishes the dropdown just disappears.

This is fixed in v3.2.1 RC 1.
