### ISSUE TITLE
Oxygen 3.2 New Editable Breakpoints Problem

### ISSUE THREAD

**Issue by Sausse** [soflyy/oxygen-bugs-and-features#878]
**Describe the bug**
When selecting a breakpoint to view, the wrong breakpoint width is displayed.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
Yes. https://oxygen-q6lmmmkhfpd8k.oxygen-demo.qsandbox.me/?ct_builder=true&amp%3Bct_inner=true

**To Reproduce**
1. Go to any page
2. Click on Breakpoint selector
3. Selector 'All devices'. Behaves fine.
4. Selector 'Page container (1120px) and below. Actual width displayed is 992px.
5. Selector 'Less than 992px. Actual width displayed is 768px.
6. Selector 'Less than 768px'. Actual width displayed is 480px.
7. Selector 'Less than 480px'. Actual width displayed is 480px (Same as step 6).

**Expected behavior**
Expect correct width to display for selected breakpoint.

**Desktop (please complete the following information):**
 - Windows 10
 - Browser Firefox
 - Oxygen Version 3.2

**Comment by KittenCodes** [comment]
@Sausse 

This is the intended behaviour. When selecting a break point (such as 992px), the builder will display at the next smallest break point, plus 1px. This is so that you can make sure that the settings changed on the 992px break point will look correct on the smallest screen that uses that break point.
