### ISSUE TITLE
German umlauts

### ISSUE THREAD

**Issue by 2crstn** [soflyy/oxygen-bugs-and-features#903]
After saving a page in WordPress (not Oxygen), all German umlauts in Oxygen get replaced by curious characters – for example `ü` gets replaced with `Â¼` or similar.

Database collation is set as `utf8_general_ci`.

The issue only occurs on one customer website – so far.

![Bildschirmfoto 2020-03-17 um 13 40 52](https://user-images.githubusercontent.com/34264572/76857076-01cde100-6855-11ea-83c9-d3c7f5c32311.png)

The site uses Oxygen 2.4 – a strange thing is that an update through WordPress does not work.

We can setup a private test site with an admin user, if you need that.

We will test the bug in a different environment soon.

**Comment by 2crstn** [comment]
The website is hosted on Strato with PHP 7.3 and MySQL 5.6.42, during development we had no such issues on our servers (Mittwald).

I don't know how MySQL is setup at Strato but I think there should be an Oxygen manual page that lists issues with specific hosting providers.

**Comment by KittenCodes** [comment]
@2crstn 

> The site uses Oxygen 2.4 – a strange thing is that an update through WordPress does not work.

Please update to v3.2 manually by following these steps:

- **Take a full backup of your site**
- Deactivate and delete Oxygen
- Download the latest version from the customer portal: https://oxygenbuilder.com/portal
- Install it via the Plugins page on your site

Please then clear caches (browser, server and plugin).

If you continue to experience the behaviour, please open a support ticket so that we can take a look at the site: https://oxygenbuilder.com/support.

**Comment by NetOldie** [comment]
@2crstn 

This does not look like an oxygen problem.
Rather, it is most likely due to the different character sets of the databases.

Try the database collation set with the setting utf8mb4.

**Comment by rorar** [comment]
Add this to the .htaccess file:
```AddDefaultCharset UTF-8
AddDefaultCharset ISO-8859-1```

and this to the wp-config.php file right after the first line "<php":

```ini_set( 'default_charset', 'UTF-8' );```

best solution: leave Strato behind... Old sluggish stack, their FastCGI implementation creates problems out of nowhere, just MySQL - No MariaDB (which is 24% faster than MySQL),...
